<script lang="ts">
    import Header from '@components/app/Header.svelte';
    import Page from '@components/app/Page.svelte';
    import MarkupHTMLView from '@components/concepts/MarkupHTMLView.svelte';
    import ProjectView from '@components/project/ProjectView.svelte';
    import Checkbox from '@components/widgets/Checkbox.svelte';
    import LocalizedText from '@components/widgets/LocalizedText.svelte';
    import {
        FieldPath,
        and,
        collection,
        doc,
        getDoc,
        getDocs,
        limit,
        or,
        orderBy,
        query,
        startAfter,
        where,
        type DocumentData,
        type QueryDocumentSnapshot,
    } from 'firebase/firestore';
    import { onMount } from 'svelte';
    import { writable } from 'svelte/store';
    import Spinning from '@components/app/Spinning.svelte';
    import { getUser, setConceptPath } from '@components/project/Contexts';
    import Button from '@components/widgets/Button.svelte';
    import { DB, disconnected, locales } from '@db/Database';
    import { Projects } from '@db/projects/Projects';
    import { firestore } from '@db/firebase';
    import type { ModerationState } from '@db/projects/Moderation';
    import {
        Flags,
        getFlagDescription,
        isModerator,
        unknownFlags,
        withFlag,
    } from '@db/projects/Moderation';
    import type Project from '@db/projects/Project';
    import { ProjectsCollection } from '@db/projects/ProjectsDatabase.svelte';
    import moderateProject from '@db/projects/moderateProject';
    import {
        StrikesCollection,
        StrikesUntilBanned,
    } from '@db/creators/strikes.svelte';
    import ConfirmButton from '@components/widgets/ConfirmButton.svelte';

    /** Where reports of public content live. Only moderators can read them. */
    const ReportsCollection = 'reports';
    /** How many unresolved reports to look at when finding the next one, so a
     *  moderator can pass on several in a row. */
    const ReportsPerLook = 20;

    /** A fresh decision id. Matches Database.getWriterID()'s guarded approach
     *  rather than pulling `uuid` into a route: `crypto.randomUUID` is missing
     *  on older Safari and in some non-secure contexts. */
    function newDecisionID(): string {
        return typeof crypto !== 'undefined' && crypto.randomUUID
            ? crypto.randomUUID()
            : `d-${Math.random().toString(36).slice(2)}-${Date.now().toString(36)}`;
    }

    const user = getUser();

    /** Moderator if the user's "mod" custom claim is true */
    let moderator: boolean | undefined = $state(undefined);
    $effect(() => {
        if ($user) {
            isModerator($user).then((mod) => {
                moderator = mod;
            });
        } else {
            moderator = false;
        }
    });

    /** The cursor into the unmoderated queue; undefined once it's exhausted.
     *  Only ever a position, never a signal about what's on screen — a
     *  reported project jumps the queue without touching it, and overloading
     *  it left the whole panel stuck on a spinner. */
    let lastBatch: QueryDocumentSnapshot<DocumentData> | null | undefined =
        $state(null);
    /** Whether we're still looking for something to review. */
    let loading = $state(true);
    /** Whether there's nothing left to review. */
    let done = $state(false);
    let project: Project | undefined = $state(undefined);

    let newFlags: ModerationState | undefined = $state();

    /** Whether someone reported the project being shown. */
    let reported = $state(false);
    /** Reported projects this moderator passed on. Reports jump the queue by
     *  always asking for the oldest unresolved one, so without this, skipping a
     *  reported project just showed it again — the only way past it was to
     *  decide it. Kept in memory rather than resolving the report, since
     *  passing on something isn't the same as having handled it. */
    const skipped = new Set<string>();
    /** Identifies the decision being made about the project on screen, so
     *  submitting it twice warns its creator once. Set once per project shown
     *  and deliberately not regenerated by `save()`: a failed submission leaves
     *  the moderator on the same project, and pressing submit again is the
     *  obvious next move — but the call may have succeeded with only its
     *  response lost, and a spurious third warning is a ban. */
    let decision = $state('');
    /** Whether the moderator's decision attaches a warning to the creator. */
    let warnCreator = $state(true);
    /** Warnings this creator already has. */
    let ownerStrikes = $state(0);
    /** Whether the decision on screen finds anything wrong. A decision that
     *  clears a project never warns anyone, whatever the checkbox says. */
    let violates = $derived(
        Object.values(newFlags ?? {}).some((state) => state === true),
    );

    let moderatedCount = $state(0);
    let unmoderatedCount = $state(0);
    // True while a flag write is in flight, to disable the controls so a
    // moderator can't double-submit or skip past an unsaved decision.
    let saving = $state(false);
    onMount(async () => {
        try {
            await nextBatch();
        } catch (error) {
            console.error(error);
            lastBatch = undefined;
        }
    });

    // Create a concept path for children
    setConceptPath(writable([]));

    /**
     * A read, with one retry when the first attempt fails on connectivity.
     *
     * The first reads a freshly loaded page makes are the ones most likely to
     * lose their race with DB.read's budget: the app's own start-up work can
     * hold the main thread long enough that the response callback doesn't get
     * to run, which Safari reaches far more often than Chrome. This page opens
     * with two such reads back to back, and losing either one cost reported
     * content the priority this queue exists to give it. Anything that isn't a
     * connectivity failure — a rule saying no, a malformed query — answers the
     * same way twice, so it's rethrown on the spot.
     */
    async function readRetrying<T>(read: () => Promise<T>): Promise<T> {
        try {
            return await DB.read(read());
        } catch (error) {
            if (!DB.isConnectivityError(error)) throw error;
            return await DB.read(read());
        }
    }

    /**
     * The next reported project, if any. Reports come first: someone took the
     * trouble to say this one needs looking at, which is a much better signal
     * than "oldest unmoderated".
     *
     * Reports are read once per batch rather than kept in a listener — this
     * page is a queue a moderator works through, not a live feed.
     */
    async function nextReported(): Promise<string | undefined> {
        if (firestore === undefined) return undefined;
        // The closure below defers the read, so hold the checked handle:
        // narrowing doesn't reach inside a callback.
        const db = firestore;
        try {
            const reports = await readRetrying(() =>
                getDocs(
                    query(
                        collection(db, ReportsCollection),
                        where('resolved', '==', false),
                        orderBy('time'),
                        // Enough to see past the ones passed on this session.
                        // Reports are rare, so this is one small read either way.
                        limit(ReportsPerLook),
                    ),
                ),
            );
            for (const doc of reports.docs) {
                const project = doc.data()?.project;
                if (typeof project === 'string' && !skipped.has(project))
                    return project;
            }
            return undefined;
        } catch {
            // A failure here just means falling back to the unmoderated
            // queue — it's a prioritization, not the work itself.
            return undefined;
        }
    }

    async function nextBatch() {
        loading = true;
        // Every project reaches the screen through here, so this is one id per
        // time a moderator is shown something to decide about. A project that
        // comes up for review again gets a new one, which is right: it was
        // published again, so breaking the rules again is a second warning.
        decision = newDecisionID();
        try {
            await findNext();
        } finally {
            loading = false;
        }
    }

    async function findNext() {
        if (firestore === undefined) {
            done = true;
            return;
        }
        const db = firestore;

        // Reported content jumps the queue.
        reported = false;
        const reportedID = await nextReported();
        if (reportedID !== undefined) {
            let doc;
            try {
                doc = await readRetrying(() =>
                    getDocs(
                        query(
                            collection(db, ProjectsCollection),
                            where('id', '==', reportedID),
                            limit(1),
                        ),
                    ),
                );
            } catch (error) {
                // We know a report is waiting and couldn't fetch what it names.
                // Say so and stop: falling through to the unmoderated queue
                // would quietly show other work in its place, and skipping it
                // would mark a reachable project unactionable for the session
                // over one failed read.
                DB.reportBanner((l) => l.ui.banner.loadFailed, error);
                return;
            }
            const data = doc.docs[0]?.data();
            if (data !== undefined) {
                project = await Projects.parseProject(data);
                if (project) {
                    newFlags = project.getFlags();
                    reported = true;
                    await loadOwnerStrikes();
                    return;
                }
            }
            // A report naming a project that's gone or won't parse can't be
            // acted on, and resolving it would claim it was. Pass it over for
            // this session so it doesn't cost a read on every advance.
            skipped.add(reportedID);
        }

        const unmoderated = query(
            collection(firestore, ProjectsCollection),
            // Construct a query for each flag to find any project that has a null flag.
            and(
                where('public', '==', true),
                or(
                    ...Array.from(Object.keys(Flags)).map((flag) =>
                        where(new FieldPath('flags', flag), '==', null),
                    ),
                ),
            ),
            orderBy('timestamp'),
            ...(lastBatch ? [startAfter(lastBatch)] : []),
            limit(1),
        );
        // Wrap in read() so an unreachable backend fails fast (and trips the
        // connection banner) instead of hanging the moderation queue.
        let documentSnapshots;
        try {
            documentSnapshots = await DB.read(getDocs(unmoderated));
        } catch (error) {
            // Unlike a background read, this one is user-initiated: a moderator
            // opened a tool whose entire content is this queue, so the failure
            // belongs on screen.
            DB.reportBanner((l) => l.ui.banner.loadFailed, error);
            return;
        }

        if (!lastBatch) {
            //add to total projects if there was not a last batch detected
            unmoderatedCount += documentSnapshots.docs.length;
        }

        // Remember the last document. Nothing left means the queue is empty.
        lastBatch = documentSnapshots.docs[documentSnapshots.docs.length - 1];
        if (lastBatch === undefined) {
            done = true;
            project = undefined;
            return;
        }

        // Convert the docs to galleries
        const projectData = documentSnapshots.docs.map((snap) =>
            snap.data(),
        )[0];

        project = await Projects.parseProject(projectData);

        if (project) {
            newFlags = project.getFlags();
            await loadOwnerStrikes();
        }
    }

    /** How many warnings this project's owner already has, so the moderator
     *  can see what one more would do before they do it. Readable here because
     *  the rules let moderators read anyone's record. */
    async function loadOwnerStrikes() {
        ownerStrikes = 0;
        const owner = project?.getOwner();
        if (firestore === undefined || !owner) return;
        try {
            const record = await DB.read(
                getDoc(doc(firestore, StrikesCollection, owner)),
            );
            const count = record.data()?.count;
            ownerStrikes = typeof count === 'number' ? count : 0;
        } catch {
            // Not knowing the count means the consequence text stays generic;
            // it must not stop a moderator from deciding.
            ownerStrikes = 0;
        }
    }

    async function save() {
        if (newFlags === undefined || project === undefined) return;
        if (firestore === undefined) return;
        // Treat any still-undecided (null) flag as "not flagged" before saving.
        let flags = newFlags;
        for (const [flag, state] of Object.entries(newFlags))
            if (state === null) flags = withFlag(flags, flag, false);
        newFlags = flags;

        // Write the flags with write() so the result is definitive: only
        // advance the queue (count + next project) once the write actually
        // lands. The old fire-and-forget edit advanced optimistically even when
        // the write failed, so a moderator could believe a project was handled
        // when it wasn't. On failure we surface a banner and stay put.
        saving = true;
        try {
            // Through the callable rather than a direct write: the decision
            // also warns the creator, takes the project out of public view,
            // resolves any reports about it, and — at the third warning —
            // removes their ability to make anything public. None of that is
            // the client's to do.
            await moderateProject({
                project: project.getID(),
                flags,
                strike: warnCreator && violates,
                decision,
            });
        } catch (error) {
            DB.reportBanner((l) => l.ui.banner.saveFailed, error);
            saving = false;
            return;
        }
        saving = false;

        moderatedCount += 1; //increment the moderated count when saved with new flags.
        skip();
    }

    function skip() {
        // Passing on a reported project has to be remembered, or the report
        // query hands back the same one and the button does nothing.
        const id = project?.getID();
        if (reported && id !== undefined) skipped.add(id);
        nextBatch();
    }
</script>

<Page>
    <div class="moderate">
        <div class="flags">
            <Header text={(l) => l.moderation.moderate.header} />
            {#if moderator === false}
                <p><LocalizedText path={(l) => l.moderation.error.notmod} /></p>
            {:else if loading}
                <Spinning />
            {:else if done || project === undefined}
                <p><LocalizedText path={(l) => l.moderation.done} /></p>
            {:else}
                <div class="progress-counter">
                    <MarkupHTMLView
                        markup={[
                            (l) => l.moderation.progress,
                            {
                                moderated: moderatedCount,
                                remaining: unmoderatedCount,
                            },
                        ]}
                    />
                </div>
                {#if reported}
                    <MarkupHTMLView
                        markup={(l) => l.moderation.report.flagged}
                    />
                {/if}
                <MarkupHTMLView
                    markup={(l) => l.moderation.moderate.explanation}
                />
                {#each Object.entries(project.getFlags()) as [flag, state]}
                    <div class="flag">
                        <Checkbox
                            label={(l) => l.moderation.button.property}
                            on={state === null ? undefined : state}
                            id={flag}
                            changed={(value) =>
                                (newFlags = withFlag(
                                    newFlags ?? unknownFlags(),
                                    flag,
                                    value === true,
                                ))}
                        />
                        <label for={flag}>
                            <MarkupHTMLView
                                markup={getFlagDescription(flag, $locales) ??
                                    ''}
                            /></label
                        >
                    </div>
                {/each}
                {#if violates}
                    <div class="flag">
                        <Checkbox
                            label={(l) => l.moderation.strike.issue}
                            on={warnCreator}
                            id="warn-creator"
                            changed={(value) => (warnCreator = value === true)}
                        />
                        <label for="warn-creator"
                            ><LocalizedText
                                path={(l) => l.moderation.strike.issue}
                            /></label
                        >
                    </div>
                    <!-- Say what this decision does to this person before it's
                         made, not after. -->
                    {#if warnCreator}
                        <MarkupHTMLView
                            markup={[
                                (l) => l.moderation.strike.consequence,
                                {
                                    count: ownerStrikes + 1,
                                    remaining: Math.max(
                                        0,
                                        StrikesUntilBanned - (ownerStrikes + 1),
                                    ),
                                    banning:
                                        ownerStrikes + 1 >= StrikesUntilBanned,
                                },
                            ]}
                        />
                    {/if}
                {/if}
                <div class="controls">
                    {#if violates && warnCreator}
                        <ConfirmButton
                            enabled={!$disconnected && !saving}
                            tip={(l) => l.moderation.strike.confirm.description}
                            prompt={(l) => l.moderation.strike.confirm.prompt}
                            action={save}
                            label={(l) => l.moderation.button.submit.label}
                            testid="moderate-submit"
                        />
                    {:else}
                        <Button
                            background
                            active={!$disconnected && !saving}
                            tip={(l) => l.moderation.button.submit.tip}
                            action={save}
                            testid="moderate-submit"
                            label={(l) => l.moderation.button.submit.label}
                        />
                    {/if}
                    <Button
                        background
                        active={!$disconnected && !saving}
                        tip={(l) => l.moderation.button.skip.tip}
                        action={skip}
                        label={(l) => l.moderation.button.skip.label}
                    />
                </div>
            {/if}
        </div>
        {#if lastBatch === undefined}<div class="big">✔</div
            >{:else if project === undefined}
            <Spinning />
        {:else}
            <ProjectView
                {project}
                autofocus={false}
                editable={false}
                warn={false}
            />
        {/if}
    </div>
</Page>

<style>
    .moderate {
        display: flex;
        flex-direction: row;
        flex-wrap: nowrap;
        width: 100%;
        height: 100%;
    }

    .flags {
        width: 25vw;
        display: flex;
        flex-direction: column;
        gap: var(--wordplay-spacing);
        padding: var(--wordplay-spacing);
        border-inline-end: var(--wordplay-focus-width) solid
            var(--wordplay-border-color);
        overflow-x: hidden;
        overflow-y: auto;
    }

    .flag {
        display: flex;
        flex-direction: row;
        gap: var(--wordplay-spacing);
        align-items: normal;
        font-size: medium;
    }

    .controls {
        display: flex;
        flex-direction: row;
        flex-wrap: nowrap;
        gap: var(--wordplay-spacing);
        margin-inline-start: auto;
    }

    .big {
        display: flex;
        align-items: center;
        justify-content: center;
        text-align: center;
        width: 100%;
        font-size: 120pt;
    }
</style>
