import type { Season } from './Season.ts';
import { LocalGlyph, type SeasonDesign } from './elements.ts';

/**
 * What each season puts in the page's margins, on the landing stage, and as a
 * rare regional surprise (#108). Glyphs and emoji only, never images: the
 * platform is about type, and a decorative glyph is hidden from screen readers
 * where an image would need a description in thirty languages.
 *
 * Curation rules, which every addition here is held to:
 * - Nature, weather, everyday life, and writing systems. No holidays, flags,
 *   religious symbols, or national emblems.
 * - Plants and animals only where they are native: no cactus in Africa, no
 *   penguin in the Arctic.
 * - Anything of specific cultural significance is added only after review by
 *   people of that culture. Until then it is not here at all.
 * - Calm: within AttentionBudget per screenful, so a season can be
 *   atmospheric (many faint figures) without dominating; nothing that flashes;
 *   and every motion still (not gone) for a reader who prefers reduced motion.
 */
export const SeasonDesigns: Record<Season, SeasonDesign> = {
    wet: {
        typical: 'rain',
        elements: [
            {
                // Monsoon rain: many faint danda strokes, falling fast.
                name: 'rain',
                composition: { kind: 'single', glyph: '।' },
                motion: 'pour',
                count: 26,
                size: [1, 1.4],
                duration: 1.6,
                placement: 'margin',
                tone: 'blue',
                opacity: 0.15,
                when: ['rain', 'cloud', 'wind'],
            },
            {
                // Between downpours, a lighter rain.
                name: 'drizzle',
                composition: { kind: 'single', glyph: '।' },
                motion: 'pour',
                count: 12,
                size: [0.8, 1.2],
                duration: 2.4,
                placement: 'margin',
                tone: 'blue',
                opacity: 0.12,
                when: ['clear', 'haze'],
            },
            {
                name: 'ripples',
                composition: { kind: 'row', glyphs: ['◌', '○', '◯'] },
                motion: 'glow',
                count: 2,
                size: [1.2, 1.6],
                duration: 5,
                placement: 'ground',
                tone: 'blue',
                opacity: 0.3,
            },
            {
                name: 'paper boat',
                composition: { kind: 'single', glyph: '⛵' },
                motion: 'bob',
                count: 1,
                size: [1.8, 2.2],
                duration: 4,
                placement: 'ground',
                tone: 'muted',
                opacity: 0.4,
            },
            {
                name: 'lotus',
                composition: { kind: 'single', glyph: '🪷' },
                motion: 'sway',
                count: 1,
                size: [1.8, 2.2],
                duration: 6,
                placement: 'ground',
                tone: 'color',
                opacity: 0.45,
            },
        ],
        cast: { glyphs: ['☂', '।', '🐸', '🪷', '💧'], motion: 'fall' },
        eggs: {
            IN: {
                glyph: '☕',
                motion: 'rise',
                placement: 'ground',
                tone: 'color',
            },
            BD: {
                glyph: '☕',
                motion: 'rise',
                placement: 'ground',
                tone: 'color',
            },
            BR: {
                glyph: '🦜',
                motion: 'drift',
                placement: 'sky',
                tone: 'color',
            },
            NG: { glyph: '⌒', motion: 'glow', placement: 'sky', tone: 'muted' },
        },
    },
    dry: {
        typical: 'haze',
        elements: [
            {
                // Harmattan dust, drifting slowly.
                name: 'dust',
                composition: { kind: 'single', glyph: '·' },
                motion: 'drift',
                count: 16,
                size: [1, 1.6],
                duration: 14,
                placement: 'margin',
                tone: 'muted',
                opacity: 0.25,
            },
            {
                name: 'grass',
                composition: { kind: 'row', glyphs: ['ʬ', 'ʬ'] },
                motion: 'sway',
                count: 3,
                size: [1.2, 1.6],
                duration: 4,
                placement: 'ground',
                tone: 'highlight',
                opacity: 0.4,
            },
            {
                // A baobab: a fork of a trunk on the horizon.
                name: 'baobab',
                composition: { kind: 'stack', glyphs: ['|', 'Ψ'] },
                motion: 'still',
                count: 1,
                size: [2.8, 3.4],
                duration: 1,
                placement: 'ground',
                tone: 'muted',
                opacity: 0.35,
            },
            {
                name: 'sun',
                composition: {
                    kind: 'radial',
                    glyph: '·',
                    count: 8,
                    center: '☀',
                },
                motion: 'glow',
                count: 1,
                size: [2.2, 2.6],
                duration: 8,
                placement: 'sky',
                tone: 'orange',
                opacity: 0.4,
                when: ['clear', 'cloud'],
            },
        ],
        cast: { glyphs: ['☀', 'ʬ', '🦒', '🌾'], motion: 'drift' },
        eggs: {
            KE: {
                glyph: 'T',
                motion: 'still',
                placement: 'ground',
                tone: 'muted',
            },
            TZ: {
                glyph: '🦒',
                motion: 'drift',
                placement: 'ground',
                tone: 'color',
            },
            MX: {
                glyph: '✿',
                motion: 'fall',
                placement: 'sky',
                tone: 'purple',
            },
            ZA: {
                glyph: '✿',
                motion: 'fall',
                placement: 'sky',
                tone: 'purple',
            },
        },
    },
    hot: {
        typical: 'clear',
        elements: [
            {
                // Heat rising off the sand.
                name: 'shimmer',
                composition: { kind: 'single', glyph: '〰' },
                motion: 'rise',
                count: 14,
                size: [0.9, 1.3],
                duration: 6,
                placement: 'margin',
                tone: 'muted',
                opacity: 0.2,
            },
            {
                // A baking sun, its rays the reader's own letters.
                name: 'sun',
                composition: {
                    kind: 'radial',
                    glyph: LocalGlyph,
                    count: 8,
                    center: '☼',
                },
                motion: 'glow',
                count: 1,
                size: [2.8, 3.4],
                duration: 6,
                placement: 'sky',
                tone: 'orange',
                opacity: 0.45,
            },
            {
                name: 'dunes',
                composition: { kind: 'row', glyphs: ['﹏', '∽', '﹏'] },
                motion: 'drift',
                count: 2,
                size: [1.4, 1.8],
                duration: 16,
                placement: 'ground',
                tone: 'highlight',
                opacity: 0.35,
            },
            {
                name: 'camel',
                composition: { kind: 'single', glyph: '🐪' },
                motion: 'drift',
                count: 1,
                size: [1.8, 2.2],
                duration: 20,
                placement: 'ground',
                tone: 'color',
                opacity: 0.45,
            },
        ],
        cast: { glyphs: ['☼', '🐪', '﹏', '〰'], motion: 'rise' },
        eggs: {
            SA: {
                glyph: '🌴',
                motion: 'sway',
                placement: 'ground',
                tone: 'color',
            },
            MA: {
                glyph: '🌴',
                motion: 'sway',
                placement: 'ground',
                tone: 'color',
            },
            EG: {
                glyph: '🌴',
                motion: 'sway',
                placement: 'ground',
                tone: 'color',
            },
            AU: {
                glyph: '🦘',
                motion: 'drift',
                placement: 'ground',
                tone: 'color',
            },
            US: {
                glyph: '🌵',
                motion: 'still',
                placement: 'ground',
                tone: 'color',
            },
            MX: {
                glyph: '🌵',
                motion: 'still',
                placement: 'ground',
                tone: 'color',
            },
            CL: {
                glyph: '🌼',
                motion: 'sway',
                placement: 'ground',
                tone: 'color',
            },
        },
    },
    cool: {
        typical: 'wind',
        elements: [
            {
                name: 'stars',
                composition: { kind: 'single', glyph: '✦' },
                motion: 'glow',
                count: 20,
                size: [0.5, 0.9],
                duration: 5,
                placement: 'margin',
                tone: 'highlight',
                opacity: 0.3,
            },
            {
                name: 'moon',
                composition: { kind: 'single', glyph: '☾' },
                motion: 'bob',
                count: 1,
                size: [2.2, 2.6],
                duration: 8,
                placement: 'sky',
                tone: 'link',
                opacity: 0.45,
            },
            {
                name: 'wind',
                composition: { kind: 'single', glyph: '~' },
                motion: 'drift',
                count: 6,
                size: [1.2, 1.6],
                duration: 10,
                placement: 'margin',
                tone: 'muted',
                opacity: 0.2,
                when: ['wind', 'haze'],
            },
            {
                name: 'dunes',
                composition: { kind: 'row', glyphs: ['﹏', '∽', '﹏'] },
                motion: 'still',
                count: 1,
                size: [1.4, 1.8],
                duration: 1,
                placement: 'ground',
                tone: 'muted',
                opacity: 0.3,
            },
        ],
        cast: { glyphs: ['✦', '✧', '☾', '⋆'], motion: 'drift' },
        eggs: {
            MN: {
                glyph: '⌂',
                motion: 'still',
                placement: 'ground',
                tone: 'muted',
            },
            KZ: {
                glyph: '⌂',
                motion: 'still',
                placement: 'ground',
                tone: 'muted',
            },
            UZ: {
                glyph: '⌂',
                motion: 'still',
                placement: 'ground',
                tone: 'muted',
            },
        },
    },
    spring: {
        typical: 'clear',
        elements: [
            {
                name: 'petals',
                composition: { kind: 'single', glyph: '✿' },
                motion: 'fall',
                count: 10,
                size: [0.9, 1.3],
                duration: 10,
                placement: 'margin',
                tone: 'highlight',
                opacity: 0.35,
            },
            {
                name: 'kite',
                composition: { kind: 'stack', glyphs: ['∫', '◇'] },
                motion: 'sway',
                count: 1,
                size: [1.8, 2.2],
                duration: 5,
                placement: 'sky',
                tone: 'blue',
                opacity: 0.45,
                when: ['wind', 'clear', 'cloud'],
            },
            {
                name: 'sprouts',
                composition: { kind: 'row', glyphs: ['ɣ', 'ɣ'] },
                motion: 'sway',
                count: 3,
                size: [1.1, 1.4],
                duration: 4,
                placement: 'ground',
                tone: 'link',
                opacity: 0.4,
            },
            {
                name: 'rain',
                composition: { kind: 'single', glyph: '|' },
                motion: 'pour',
                count: 16,
                size: [0.8, 1.2],
                duration: 1.8,
                placement: 'margin',
                tone: 'blue',
                opacity: 0.12,
                when: ['rain'],
            },
        ],
        cast: { glyphs: ['✿', '❀', '🌸', '🌱'], motion: 'fall' },
        eggs: {
            JP: {
                glyph: '🌸',
                motion: 'fall',
                placement: 'sky',
                tone: 'color',
            },
            KR: {
                glyph: '🌸',
                motion: 'fall',
                placement: 'sky',
                tone: 'color',
            },
            NL: {
                glyph: '🌷',
                motion: 'sway',
                placement: 'ground',
                tone: 'color',
            },
            CN: { glyph: '❀', motion: 'fall', placement: 'sky', tone: 'pink' },
        },
    },
    summer: {
        typical: 'clear',
        elements: [
            {
                // Fireflies, brightening slowly in the warm dark.
                name: 'fireflies',
                composition: { kind: 'single', glyph: '•' },
                motion: 'glow',
                count: 12,
                size: [0.5, 0.8],
                duration: 3.5,
                placement: 'margin',
                tone: 'highlight',
                opacity: 0.45,
            },
            {
                name: 'wind chime',
                composition: { kind: 'single', glyph: '🎐' },
                motion: 'sway',
                count: 1,
                size: [1.8, 2.2],
                duration: 3.5,
                placement: 'sky',
                tone: 'color',
                opacity: 0.45,
            },
            {
                name: 'sun',
                composition: {
                    kind: 'radial',
                    glyph: LocalGlyph,
                    count: 6,
                    center: '☀',
                },
                motion: 'glow',
                count: 1,
                size: [2.4, 3],
                duration: 8,
                placement: 'sky',
                tone: 'orange',
                opacity: 0.4,
                when: ['clear', 'wind', 'haze'],
            },
            {
                name: 'watermelon',
                composition: { kind: 'single', glyph: '🍉' },
                motion: 'still',
                count: 1,
                size: [1.8, 2.2],
                duration: 1,
                placement: 'ground',
                tone: 'color',
                opacity: 0.45,
            },
        ],
        cast: { glyphs: ['☀', '🍉', '🎐', '•'], motion: 'drift' },
        eggs: {
            IN: {
                glyph: '🥭',
                motion: 'still',
                placement: 'ground',
                tone: 'color',
            },
            IT: {
                glyph: '🍋',
                motion: 'still',
                placement: 'ground',
                tone: 'color',
            },
            ES: {
                glyph: '🍋',
                motion: 'still',
                placement: 'ground',
                tone: 'color',
            },
            GR: {
                glyph: '🍋',
                motion: 'still',
                placement: 'ground',
                tone: 'color',
            },
            AU: {
                glyph: '⛱',
                motion: 'still',
                placement: 'ground',
                tone: 'color',
            },
            NZ: {
                glyph: '⛱',
                motion: 'still',
                placement: 'ground',
                tone: 'color',
            },
        },
    },
    autumn: {
        typical: 'wind',
        elements: [
            {
                name: 'leaves',
                composition: { kind: 'single', glyph: '❦' },
                motion: 'fall',
                count: 8,
                size: [1.1, 1.6],
                duration: 9,
                placement: 'margin',
                tone: 'highlight',
                opacity: 0.4,
            },
            {
                name: 'geese',
                composition: { kind: 'row', glyphs: ['ᐯ', 'ᐯ', 'ᐯ'] },
                motion: 'drift',
                count: 1,
                size: [0.8, 1.1],
                duration: 16,
                placement: 'sky',
                tone: 'muted',
                opacity: 0.35,
            },
            {
                // A pile of fallen leaves that stays put, from the 2024 design.
                name: 'leaf pile',
                composition: { kind: 'row', glyphs: ['❧', '❦', '❧'] },
                motion: 'still',
                count: 1,
                size: [1.3, 1.7],
                duration: 1,
                placement: 'ground',
                tone: 'orange',
                opacity: 0.4,
            },
            {
                name: 'wind',
                composition: { kind: 'single', glyph: '~' },
                motion: 'drift',
                count: 6,
                size: [1.2, 1.6],
                duration: 8,
                placement: 'margin',
                tone: 'muted',
                opacity: 0.2,
                when: ['wind'],
            },
        ],
        cast: { glyphs: ['❦', '❧', '🍂', '🍁'], motion: 'fall' },
        eggs: {
            KR: {
                glyph: '🟠',
                motion: 'sway',
                placement: 'sky',
                tone: 'color',
            },
            JP: {
                glyph: '🟠',
                motion: 'sway',
                placement: 'sky',
                tone: 'color',
            },
            // Not the maple leaf: it is Canada's flag.
            CA: {
                glyph: '🐿',
                motion: 'drift',
                placement: 'ground',
                tone: 'color',
            },
            AR: {
                glyph: '🍂',
                motion: 'fall',
                placement: 'sky',
                tone: 'color',
            },
            CN: {
                glyph: '🍂',
                motion: 'fall',
                placement: 'sky',
                tone: 'color',
            },
        },
    },
    winter: {
        typical: 'snow',
        elements: [
            {
                // Snowflakes: six of the reader's own letter, rotated.
                name: 'snowflakes',
                composition: { kind: 'radial', glyph: LocalGlyph, count: 6 },
                motion: 'fall',
                count: 18,
                size: [0.9, 1.5],
                duration: 12,
                placement: 'margin',
                tone: 'link',
                opacity: 0.3,
                when: ['snow', 'cloud', 'clear', 'wind'],
            },
            {
                name: 'drizzle',
                composition: { kind: 'single', glyph: ',' },
                motion: 'pour',
                count: 20,
                size: [0.9, 1.2],
                duration: 2.2,
                placement: 'margin',
                tone: 'blue',
                opacity: 0.15,
                when: ['rain'],
            },
            {
                // A snowman of round letters, bobbing.
                name: 'snowman',
                composition: { kind: 'stack', glyphs: ['O', 'o', '∘'] },
                motion: 'bob',
                count: 1,
                size: [2.4, 2.8],
                duration: 4,
                placement: 'ground',
                tone: 'foreground',
                opacity: 0.45,
                when: ['snow', 'cloud', 'clear', 'wind'],
            },
            {
                name: 'frost',
                composition: { kind: 'single', glyph: '❅' },
                motion: 'glow',
                count: 3,
                size: [0.9, 1.3],
                duration: 7,
                placement: 'margin',
                tone: 'muted',
                opacity: 0.3,
            },
        ],
        cast: { glyphs: ['❄', '❅', '❆', '⛄'], motion: 'fall' },
        eggs: {
            JP: {
                glyph: '⛄',
                motion: 'bob',
                placement: 'ground',
                tone: 'color',
            },
            FI: {
                glyph: '○',
                motion: 'still',
                placement: 'ground',
                tone: 'blue',
            },
            RU: {
                glyph: '|',
                motion: 'still',
                placement: 'ground',
                tone: 'muted',
            },
            CA: {
                glyph: '🦌',
                motion: 'drift',
                placement: 'ground',
                tone: 'color',
            },
        },
    },
    polarDay: {
        typical: 'clear',
        elements: [
            {
                // The midnight sun, circling low and never setting.
                name: 'midnight sun',
                composition: {
                    kind: 'radial',
                    glyph: '·',
                    count: 8,
                    center: '☀',
                },
                motion: 'orbit',
                count: 1,
                size: [2.2, 2.6],
                duration: 18,
                placement: 'sky',
                tone: 'highlight',
                opacity: 0.45,
            },
            {
                name: 'tundra flowers',
                composition: { kind: 'row', glyphs: ['❀', '·', '❀'] },
                motion: 'sway',
                count: 3,
                size: [0.9, 1.2],
                duration: 4,
                placement: 'ground',
                tone: 'pink',
                opacity: 0.4,
            },
            {
                name: 'ice',
                composition: { kind: 'single', glyph: '▱' },
                motion: 'drift',
                count: 4,
                size: [1.3, 1.8],
                duration: 14,
                placement: 'ground',
                tone: 'blue',
                opacity: 0.35,
            },
            {
                name: 'birds',
                composition: { kind: 'single', glyph: 'ᐯ' },
                motion: 'drift',
                count: 5,
                size: [0.7, 1],
                duration: 10,
                placement: 'sky',
                tone: 'muted',
                opacity: 0.3,
            },
        ],
        cast: { glyphs: ['☀', '❀', '▱', '🧊'], motion: 'drift' },
        eggs: {
            NO: {
                glyph: '🦌',
                motion: 'drift',
                placement: 'ground',
                tone: 'color',
            },
            SE: {
                glyph: '🦌',
                motion: 'drift',
                placement: 'ground',
                tone: 'color',
            },
            GL: {
                glyph: '🐻‍❄️',
                motion: 'drift',
                placement: 'ground',
                tone: 'color',
            },
            AQ: {
                glyph: '🐧',
                motion: 'bob',
                placement: 'ground',
                tone: 'color',
            },
        },
    },
    polarNight: {
        typical: 'clear',
        elements: [
            {
                // An aurora: bands of waves, shifting slowly.
                name: 'aurora',
                composition: { kind: 'row', glyphs: ['≋', '∿', '≋', '∿'] },
                motion: 'drift',
                count: 2,
                size: [1.4, 2],
                duration: 12,
                placement: 'sky',
                tone: 'highlight',
                opacity: 0.4,
            },
            {
                name: 'stars',
                composition: { kind: 'single', glyph: '✦' },
                motion: 'glow',
                count: 20,
                size: [0.5, 0.9],
                duration: 5,
                placement: 'margin',
                tone: 'link',
                opacity: 0.3,
            },
            {
                name: 'snow',
                composition: { kind: 'single', glyph: '·' },
                motion: 'fall',
                count: 10,
                size: [0.9, 1.3],
                duration: 12,
                placement: 'margin',
                tone: 'muted',
                opacity: 0.25,
                when: ['snow', 'wind'],
            },
            {
                name: 'window',
                composition: { kind: 'single', glyph: '▢' },
                motion: 'glow',
                count: 1,
                size: [1.4, 1.8],
                duration: 9,
                placement: 'ground',
                tone: 'orange',
                opacity: 0.45,
            },
        ],
        cast: { glyphs: ['✦', '≋', '∿', '❄'], motion: 'drift' },
        eggs: {
            NO: {
                glyph: '🦌',
                motion: 'drift',
                placement: 'ground',
                tone: 'color',
            },
            GL: {
                glyph: '🐻‍❄️',
                motion: 'drift',
                placement: 'ground',
                tone: 'color',
            },
            AQ: {
                glyph: '🐧',
                motion: 'bob',
                placement: 'ground',
                tone: 'color',
            },
        },
    },
};
