import { Sym, type SymType } from '@nodes/Sym';

const TokenCategoryDelimiter = 'delimiter';
const TokenCategoryRelation = 'relation';
const TokenCategoryShare = 'share';
const TokenCategoryEvaluation = 'eval';
const TokenCategoryDocs = 'docs';
const TokenCategoryLiteral = 'literal';
const TokenCategoryName = 'name';
const TokenCategoryType = 'type';
const TokenCategoryOperator = 'operator';
const TokenCategoryUnknown = 'unknown';
const TokenCategoryPlaceholder = 'placeholder';
const TokenCategoryEnd = 'end';

const TokenCategories: Map<SymType, string> = new Map();
TokenCategories.set(Sym.EvalOpen, TokenCategoryDelimiter);
TokenCategories.set(Sym.EvalClose, TokenCategoryDelimiter);
TokenCategories.set(Sym.SetOpen, TokenCategoryDelimiter);
TokenCategories.set(Sym.SetClose, TokenCategoryDelimiter);
TokenCategories.set(Sym.ListOpen, TokenCategoryDelimiter);
TokenCategories.set(Sym.ListClose, TokenCategoryDelimiter);
TokenCategories.set(Sym.TableOpen, TokenCategoryDelimiter);
TokenCategories.set(Sym.TableClose, TokenCategoryDelimiter);
TokenCategories.set(Sym.TypeOpen, TokenCategoryDelimiter);
TokenCategories.set(Sym.TypeClose, TokenCategoryDelimiter);
TokenCategories.set(Sym.Bind, TokenCategoryRelation);
TokenCategories.set(Sym.Access, TokenCategoryRelation);
TokenCategories.set(Sym.Function, TokenCategoryEvaluation);
TokenCategories.set(Sym.Borrow, TokenCategoryShare);
TokenCategories.set(Sym.Share, TokenCategoryShare);
TokenCategories.set(Sym.Convert, TokenCategoryEvaluation);
TokenCategories.set(Sym.Doc, TokenCategoryDocs);
TokenCategories.set(Sym.Words, TokenCategoryLiteral);
TokenCategories.set(Sym.Link, TokenCategoryType);
TokenCategories.set(Sym.Concept, TokenCategoryType);
TokenCategories.set(Sym.None, TokenCategoryLiteral);
TokenCategories.set(Sym.Type, TokenCategoryRelation);
TokenCategories.set(Sym.Literal, TokenCategoryRelation);
TokenCategories.set(Sym.Separator, TokenCategoryDelimiter);
TokenCategories.set(Sym.Language, TokenCategoryDelimiter);
TokenCategories.set(Sym.BooleanType, TokenCategoryLiteral);
TokenCategories.set(Sym.NumberType, TokenCategoryType);
TokenCategories.set(Sym.HanNumeral, TokenCategoryLiteral);
TokenCategories.set(Sym.RomanNumeral, TokenCategoryLiteral);
TokenCategories.set(Sym.ThaiNumeral, TokenCategoryLiteral);
TokenCategories.set(Sym.BengaliNumeral, TokenCategoryLiteral);
TokenCategories.set(Sym.DevanagariNumeral, TokenCategoryLiteral);
TokenCategories.set(Sym.GujaratiNumeral, TokenCategoryLiteral);
TokenCategories.set(Sym.GurmukhiNumeral, TokenCategoryLiteral);
TokenCategories.set(Sym.KannadaNumeral, TokenCategoryLiteral);
TokenCategories.set(Sym.TamilNumeral, TokenCategoryLiteral);
TokenCategories.set(Sym.TeluguNumeral, TokenCategoryLiteral);
TokenCategories.set(Sym.Pi, TokenCategoryLiteral);
TokenCategories.set(Sym.Infinity, TokenCategoryLiteral);
TokenCategories.set(Sym.Select, TokenCategoryOperator);
TokenCategories.set(Sym.Insert, TokenCategoryOperator);
TokenCategories.set(Sym.Update, TokenCategoryOperator);
TokenCategories.set(Sym.Delete, TokenCategoryOperator);
TokenCategories.set(Sym.Union, TokenCategoryOperator);
TokenCategories.set(Sym.Exponent, TokenCategoryOperator);
TokenCategories.set(Sym.Product, TokenCategoryOperator);
TokenCategories.set(Sym.Percent, TokenCategoryOperator);
TokenCategories.set(Sym.Change, TokenCategoryOperator);
TokenCategories.set(Sym.Previous, TokenCategoryOperator);
TokenCategories.set(Sym.Change, TokenCategoryOperator);
TokenCategories.set(Sym.Placeholder, TokenCategoryPlaceholder);
TokenCategories.set(Sym.Operator, TokenCategoryOperator);
TokenCategories.set(Sym.Conditional, TokenCategoryOperator);
TokenCategories.set(Sym.Otherwise, TokenCategoryOperator);
TokenCategories.set(Sym.Match, TokenCategoryOperator);
TokenCategories.set(Sym.Text, TokenCategoryLiteral);
// Formatted text is a text type, so color its `…` delimiter like Text.
TokenCategories.set(Sym.FormattedType, TokenCategoryLiteral);
TokenCategories.set(Sym.Code, TokenCategoryDocs);
TokenCategories.set(Sym.Number, TokenCategoryLiteral);
TokenCategories.set(Sym.Decimal, TokenCategoryLiteral);
TokenCategories.set(Sym.Base, TokenCategoryLiteral);
TokenCategories.set(Sym.Boolean, TokenCategoryLiteral);
TokenCategories.set(Sym.Name, TokenCategoryName);
TokenCategories.set(Sym.End, TokenCategoryEnd);
TokenCategories.set(Sym.Unknown, TokenCategoryUnknown);
TokenCategories.set(Sym.TagOpen, TokenCategoryDelimiter);
TokenCategories.set(Sym.TagClose, TokenCategoryDelimiter);
TokenCategories.set(Sym.URL, TokenCategoryShare);

// Pattern tokens. The delimiter `⣿` and raw quoted text read like text literals;
// character classes, quantifiers, anchors, and the other matching operators read
// like operators. Capture/property names reuse Sym.Name above, so they're already
// name-colored. (Coloring keys on the token's first Sym type; pattern glyphs that
// double as other symbols list their Pattern* type first — see PatternTokenPatterns.)
TokenCategories.set(Sym.PatternDelimiter, TokenCategoryLiteral);
TokenCategories.set(Sym.PatternText, TokenCategoryLiteral);
TokenCategories.set(Sym.PatternAny, TokenCategoryOperator);
TokenCategories.set(Sym.PatternLetter, TokenCategoryOperator);
TokenCategories.set(Sym.PatternDigit, TokenCategoryOperator);
TokenCategories.set(Sym.PatternSpace, TokenCategoryOperator);
TokenCategories.set(Sym.PatternRest, TokenCategoryOperator);
TokenCategories.set(Sym.PatternWord, TokenCategoryOperator);
TokenCategories.set(Sym.PatternWordEdge, TokenCategoryOperator);
TokenCategories.set(Sym.PatternStart, TokenCategoryOperator);
TokenCategories.set(Sym.PatternEnd, TokenCategoryOperator);
TokenCategories.set(Sym.PatternAhead, TokenCategoryOperator);
TokenCategories.set(Sym.PatternBehind, TokenCategoryOperator);
TokenCategories.set(Sym.PatternFold, TokenCategoryOperator);
TokenCategories.set(Sym.PatternRange, TokenCategoryOperator);
TokenCategories.set(Sym.PatternComplement, TokenCategoryOperator);
TokenCategories.set(Sym.PatternAlternation, TokenCategoryOperator);
TokenCategories.set(Sym.PatternSlash, TokenCategoryOperator);
TokenCategories.set(Sym.PatternEqual, TokenCategoryOperator);
TokenCategories.set(Sym.PatternGreater, TokenCategoryOperator);
TokenCategories.set(Sym.PatternGreaterEqual, TokenCategoryOperator);
TokenCategories.set(Sym.PatternLess, TokenCategoryOperator);
TokenCategories.set(Sym.PatternLessEqual, TokenCategoryOperator);

export default TokenCategories;
