/**
 * The single hand-authored source of truth for every bundled font (except the
 * 3 emoji families, whose bespoke CSS lives in scripts/fonts/emoji.ts). Carries
 * only policy a cmap can't express; unicode-ranges are generated into
 * faces.generated.ts + the CSS files and captured in fonts.lock.json.
 *
 * Edit this to add/change a font, then run `npm run fonts-fix` (whole-file
 * faces) or `npm run fonts-download` (Google-sliced faces).
 */
import type { Script } from '@locale/Scripts';
import type { FontWeight, FontWeightRange } from './Fonts';

export type FontManifestEntry = {
    /** CSS font-family name. */
    readonly name: string;
    /** creator = pickable in the font chooser; fallback = in the lazy chain. */
    readonly roles: readonly ('creator' | 'fallback')[];
    /** preload = declared in a CSS file; ondemand = loaded via FontManager. */
    readonly delivery: 'preload' | 'ondemand';
    /** google = Google's lazy-load slice partition (re-fetch to repair);
     *  cmap = whole-file coverage (`npm run fonts-fix` re-derives);
     *  emoji = whole-file cmap ∩ the emoji blocks + sequence format chars;
     *  preserve = keep the captured range verbatim (decorative faces). */
    readonly rangeSource: 'google' | 'cmap' | 'emoji' | 'preserve';
    readonly scripts: readonly Script[];
    readonly weights: FontWeightRange | readonly FontWeight[];
    readonly italic: boolean;
    readonly format: 'ttf' | 'otf' | 'woff2';
    /** Google Fonts family name for `npm run fonts-download`. */
    readonly source: string;
    /** Generic escape hatch for bespoke faces (e.g. emoji) whose CSS can't be
     *  mechanically generated. When present, the generator inlines this CSS
     *  partial (a hand-authored island) into the target stylesheet verbatim
     *  and skips mechanical @font-face emission for the emoji faces; their
     *  ranges are still cmap-guarded by the drift test. */
    readonly override?: {
        readonly cssPartial: string;
        readonly target: 'fonts.css' | 'fonts-fallback.css';
    };
};

export const FontManifest: readonly FontManifestEntry[] = [
    // Emoji: bespoke @font-face structure (mono `block` face, Safari SVG
    // @supports branch, 10 color slices, the class-only keycap face) lives in
    // the hand-authored island emoji-faces.css, inlined via the override below.
    // Ranges are still cmap-derived (rangeSource 'emoji') and drift-guarded.
    {
        name: 'Noto Emoji',
        roles: ['creator'],
        delivery: 'preload',
        rangeSource: 'emoji',
        scripts: ['Emoj'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Emoji',
        override: { cssPartial: 'emoji-faces.css', target: 'fonts.css' },
    },
    {
        name: 'Noto Color Emoji',
        roles: ['creator'],
        delivery: 'preload',
        rangeSource: 'emoji',
        scripts: ['Emoj'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Color Emoji',
    },
    {
        name: 'Aclonica',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Aclonica',
    },
    {
        name: 'Arvo',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400, 700],
        italic: true,
        format: 'woff2',
        source: 'Arvo',
    },
    {
        name: 'Berkshire Swash',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Berkshire Swash',
    },
    {
        name: 'Black Han Sans',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn', 'Hang'],
        weights: [400],
        italic: false,
        format: 'ttf',
        source: 'Black Han Sans',
    },
    {
        name: 'Borel',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Borel',
    },
    {
        name: 'Broadway',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'ttf',
        source: 'Broadway',
    },
    {
        name: 'Bungee Outline',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Bungee Outline',
    },
    {
        name: 'Cabin Sketch',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400, 700],
        italic: false,
        format: 'woff2',
        source: 'Cabin Sketch',
    },
    {
        name: 'Carter One',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Carter One',
    },
    {
        name: 'Caveat',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn', 'Cyrl'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Caveat',
    },
    {
        name: 'Codystar',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [300, 400],
        italic: false,
        format: 'woff2',
        source: 'Codystar',
    },
    {
        name: 'Comic Neue',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [300, 400, 700],
        italic: true,
        format: 'ttf',
        source: 'Comic Neue',
    },
    {
        name: 'Courier Prime',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400, 700],
        italic: true,
        format: 'ttf',
        source: 'Courier Prime',
    },
    {
        name: 'Crafty Girls',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Crafty Girls',
    },
    {
        name: 'Creepster',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Creepster',
    },
    {
        name: 'Delius',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'ttf',
        source: 'Delius',
    },
    {
        name: 'Dot Gothic 16',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn', 'Hira', 'Kana', 'Hani', 'Cyrl'],
        weights: [400],
        italic: false,
        format: 'ttf',
        source: 'Dot Gothic 16',
    },
    {
        name: 'Doto',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Doto',
    },
    {
        name: 'Dreaming Outloud',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'otf',
        source: 'Dreaming Outloud',
    },
    {
        name: 'Gorditas',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400, 700],
        italic: false,
        format: 'woff2',
        source: 'Gorditas',
    },
    {
        name: 'Graduate',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Graduate',
    },
    {
        name: 'Hi Melody',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn', 'Hira', 'Kana', 'Hani', 'Cyrl'],
        weights: [400],
        italic: false,
        format: 'ttf',
        source: 'Hi Melody',
    },
    {
        name: 'Luckiest Guy',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Luckiest Guy',
    },
    {
        name: 'Megrim',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn', 'Cyrl'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Megrim',
    },
    {
        name: 'Merriweather',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: { min: 300, max: 900 },
        italic: true,
        format: 'ttf',
        source: 'Merriweather',
    },
    {
        name: 'Modak',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn', 'Deva'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Modak',
    },
    {
        name: 'Modern Love',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'ttf',
        source: 'Modern Love',
    },
    {
        name: 'Monoton',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Monoton',
    },
    {
        name: 'Mouse Memoirs',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Mouse Memoirs',
    },
    {
        name: 'Noto Music',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: [],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Music',
    },
    {
        name: 'Noto Sans',
        roles: ['creator'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Latn', 'Cyrl', 'Grek'],
        weights: [300, 400, 700, 900],
        italic: true,
        format: 'woff2',
        source: 'Noto Sans',
    },
    {
        name: 'Noto Sans Adlam',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Adlm'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Adlam',
    },
    {
        name: 'Noto Sans Anatolian Hieroglyphs',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Hluw'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Anatolian Hieroglyphs',
    },
    {
        name: 'Noto Sans Arabic',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Arab'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Arabic',
    },
    {
        name: 'Noto Sans Armenian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Armn'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Armenian',
    },
    {
        name: 'Noto Sans Avestan',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Avst'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Avestan',
    },
    {
        name: 'Noto Sans Balinese',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Bali'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Balinese',
    },
    {
        name: 'Noto Sans Bamum',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Bamu'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Bamum',
    },
    {
        name: 'Noto Sans Bassa Vah',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Bass'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Bassa Vah',
    },
    {
        name: 'Noto Sans Batak',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Batk'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Batak',
    },
    {
        name: 'Noto Sans Bengali',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Beng'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Bengali',
    },
    {
        name: 'Noto Sans Bhaiksuki',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Bhks'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Bhaiksuki',
    },
    {
        name: 'Noto Sans Brahmi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Brah'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Brahmi',
    },
    {
        name: 'Noto Sans Buginese',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Bugi'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Buginese',
    },
    {
        name: 'Noto Sans Buhid',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Buhd'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Buhid',
    },
    {
        name: 'Noto Sans Canadian Aboriginal',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Cans'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Canadian Aboriginal',
    },
    {
        name: 'Noto Sans Carian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Cari'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Carian',
    },
    {
        name: 'Noto Sans Caucasian Albanian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Aghb'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Caucasian Albanian',
    },
    {
        name: 'Noto Sans Chakma',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Cakm'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Chakma',
    },
    {
        name: 'Noto Sans Cham',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Cham'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Cham',
    },
    {
        name: 'Noto Sans Cherokee',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Cher'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Cherokee',
    },
    {
        name: 'Noto Sans Chorasmian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Chrs'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Chorasmian',
    },
    {
        name: 'Noto Sans Coptic',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Copt'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Coptic',
    },
    {
        name: 'Noto Sans Cuneiform',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Xsux'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Cuneiform',
    },
    {
        name: 'Noto Sans Cypriot',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Cprt'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Cypriot',
    },
    {
        name: 'Noto Sans Cypro Minoan',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Cpmn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Cypro Minoan',
    },
    {
        name: 'Noto Sans Deseret',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Dsrt'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Deseret',
    },
    {
        name: 'Noto Sans Devanagari',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Deva'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Devanagari',
    },
    {
        name: 'Noto Sans Duployan',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Dupl'],
        weights: [400, 700],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Duployan',
    },
    {
        name: 'Noto Sans Egyptian Hieroglyphs',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Egyp'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Egyptian Hieroglyphs',
    },
    {
        name: 'Noto Sans Elbasan',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Elba'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Elbasan',
    },
    {
        name: 'Noto Sans Elymaic',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Elym'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Elymaic',
    },
    {
        name: 'Noto Sans Ethiopic',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Ethi'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Ethiopic',
    },
    {
        name: 'Noto Sans Georgian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Geor'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Georgian',
    },
    {
        name: 'Noto Sans Glagolitic',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Glag'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Glagolitic',
    },
    {
        name: 'Noto Sans Gothic',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Goth'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Gothic',
    },
    {
        name: 'Noto Sans Grantha',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Gran'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Grantha',
    },
    {
        name: 'Noto Sans Gujarati',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Gujr'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Gujarati',
    },
    {
        name: 'Noto Sans Gunjala Gondi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Gong'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Gunjala Gondi',
    },
    {
        name: 'Noto Sans Gurmukhi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Guru'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Gurmukhi',
    },
    {
        name: 'Noto Sans Hanifi Rohingya',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Rohg'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Hanifi Rohingya',
    },
    {
        name: 'Noto Sans Hanunoo',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Hano'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Hanunoo',
    },
    {
        name: 'Noto Sans Hatran',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Hatr'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Hatran',
    },
    {
        name: 'Noto Sans Hebrew',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Hebr'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Hebrew',
    },
    {
        name: 'Noto Sans Imperial Aramaic',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Armi'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Imperial Aramaic',
    },
    {
        name: 'Noto Sans Inscriptional Pahlavi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Phli'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Inscriptional Pahlavi',
    },
    {
        name: 'Noto Sans Inscriptional Parthian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Prti'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Inscriptional Parthian',
    },
    {
        name: 'Noto Sans Japanese',
        roles: ['creator', 'fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Hira', 'Kana', 'Hani'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Japanese',
    },
    {
        name: 'Noto Sans Javanese',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Java'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Javanese',
    },
    {
        name: 'Noto Sans Kaithi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Kthi'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Kaithi',
    },
    {
        name: 'Noto Sans Kannada',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Knda'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Kannada',
    },
    {
        name: 'Noto Sans Kawi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Kawi'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Kawi',
    },
    {
        name: 'Noto Sans Kayah Li',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Kali'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Kayah Li',
    },
    {
        name: 'Noto Sans Kharoshthi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Khar'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Kharoshthi',
    },
    {
        name: 'Noto Sans Khmer',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Khmr'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Khmer',
    },
    {
        name: 'Noto Sans Khojki',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Khoj'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Khojki',
    },
    {
        name: 'Noto Sans Khudawadi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Sind'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Khudawadi',
    },
    {
        name: 'Noto Sans Korean',
        roles: ['creator', 'fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Hang'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Korean',
    },
    {
        name: 'Noto Sans Lao',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Laoo'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Lao',
    },
    {
        name: 'Noto Sans Lepcha',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Lepc'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Lepcha',
    },
    {
        name: 'Noto Sans Limbu',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Limb'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Limbu',
    },
    {
        name: 'Noto Sans Linear A',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Lina'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Linear A',
    },
    {
        name: 'Noto Sans Linear B',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Linb'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Linear B',
    },
    {
        name: 'Noto Sans Lisu',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Lisu'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Lisu',
    },
    {
        name: 'Noto Sans Lycian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Lyci'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Lycian',
    },
    {
        name: 'Noto Sans Lydian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Lydi'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Lydian',
    },
    {
        name: 'Noto Sans Mahajani',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Mahj'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Mahajani',
    },
    {
        name: 'Noto Sans Malayalam',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Mlym'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Malayalam',
    },
    {
        name: 'Noto Sans Mandaic',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Mand'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Mandaic',
    },
    {
        name: 'Noto Sans Manichaean',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Mani'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Manichaean',
    },
    {
        name: 'Noto Sans Marchen',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Marc'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Marchen',
    },
    {
        name: 'Noto Sans Masaram Gondi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Gonm'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Masaram Gondi',
    },
    {
        name: 'Noto Sans Math',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: [],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Math',
    },
    {
        name: 'Noto Sans Medefaidrin',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Medf'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Medefaidrin',
    },
    {
        name: 'Noto Sans Meetei Mayek',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Mtei'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Meetei Mayek',
    },
    {
        name: 'Noto Sans Mende Kikakui',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Mend'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Mende Kikakui',
    },
    {
        name: 'Noto Sans Meroitic',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Merc', 'Mero'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Meroitic',
    },
    {
        name: 'Noto Sans Miao',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Plrd'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Miao',
    },
    {
        name: 'Noto Sans Modi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Modi'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Modi',
    },
    {
        name: 'Noto Sans Mongolian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Mong'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Mongolian',
    },
    {
        name: 'Noto Sans Mono',
        roles: ['creator'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Latn', 'Cyrl', 'Grek'],
        weights: [400, 700],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Mono',
    },
    {
        name: 'Noto Sans Mro',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Mroo'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Mro',
    },
    {
        name: 'Noto Sans Multani',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Mult'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Multani',
    },
    {
        name: 'Noto Sans Myanmar',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Mymr'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Myanmar',
    },
    {
        name: 'Noto Sans Nabataean',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Nbat'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Nabataean',
    },
    {
        name: 'Noto Sans Nag Mundari',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Nagm'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Nag Mundari',
    },
    {
        name: 'Noto Sans Nandinagari',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Nand'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Nandinagari',
    },
    {
        name: 'Noto Sans New Tai Lue',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Talu'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans New Tai Lue',
    },
    {
        name: 'Noto Sans Newa',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Newa'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Newa',
    },
    {
        name: 'Noto Sans NKo',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Nkoo'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans NKo',
    },
    {
        name: 'Noto Sans Ogham',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Ogam'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Ogham',
    },
    {
        name: 'Noto Sans Ol Chiki',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Olck'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Ol Chiki',
    },
    {
        name: 'Noto Sans Old Hungarian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Hung'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Old Hungarian',
    },
    {
        name: 'Noto Sans Old Italic',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Ital'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Old Italic',
    },
    {
        name: 'Noto Sans Old North Arabian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Narb'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Old North Arabian',
    },
    {
        name: 'Noto Sans Old Permic',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Perm'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Old Permic',
    },
    {
        name: 'Noto Sans Old Persian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Xpeo'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Old Persian',
    },
    {
        name: 'Noto Sans Old Sogdian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Sogo'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Old Sogdian',
    },
    {
        name: 'Noto Sans Old South Arabian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Sarb'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Old South Arabian',
    },
    {
        name: 'Noto Sans Old Turkic',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Orkh'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Old Turkic',
    },
    {
        name: 'Noto Sans Oriya',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Orya'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Oriya',
    },
    {
        name: 'Noto Sans Osage',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Osge'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Osage',
    },
    {
        name: 'Noto Sans Osmanya',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Osma'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Osmanya',
    },
    {
        name: 'Noto Sans Pahawh Hmong',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Hmng'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Pahawh Hmong',
    },
    {
        name: 'Noto Sans Palmyrene',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Palm'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Palmyrene',
    },
    {
        name: 'Noto Sans Pau Cin Hau',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Pauc'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Pau Cin Hau',
    },
    {
        name: 'Noto Sans PhagsPa',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Phag'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans PhagsPa',
    },
    {
        name: 'Noto Sans Phoenician',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Phnx'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Phoenician',
    },
    {
        name: 'Noto Sans Psalter Pahlavi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Phlp'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Psalter Pahlavi',
    },
    {
        name: 'Noto Sans Rejang',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Rjng'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Rejang',
    },
    {
        name: 'Noto Sans Runic',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Runr'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Runic',
    },
    {
        name: 'Noto Sans Samaritan',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Samr'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Samaritan',
    },
    {
        name: 'Noto Sans Saurashtra',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Saur'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Saurashtra',
    },
    {
        name: 'Noto Sans Sharada',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Shrd'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Sharada',
    },
    {
        name: 'Noto Sans Shavian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Shaw'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Shavian',
    },
    {
        name: 'Noto Sans Siddham',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Sidd'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Siddham',
    },
    {
        name: 'Noto Sans SignWriting',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Sgnw'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans SignWriting',
    },
    {
        name: 'Noto Sans Simplified Chinese',
        roles: ['creator', 'fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Hani', 'Hans'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Simplified Chinese',
    },
    {
        name: 'Noto Sans Sinhala',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Sinh'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Sinhala',
    },
    {
        name: 'Noto Sans Sogdian',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Sogd'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Sogdian',
    },
    {
        name: 'Noto Sans Sora Sompeng',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Sora'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Sora Sompeng',
    },
    {
        name: 'Noto Sans Soyombo',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Soyo'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Soyombo',
    },
    {
        name: 'Noto Sans Sundanese',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Sund'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Sundanese',
    },
    {
        name: 'Noto Sans Sunuwar',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Sunu'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Sunuwar',
    },
    {
        name: 'Noto Sans Syloti Nagri',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Sylo'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Syloti Nagri',
    },
    {
        name: 'Noto Sans Symbols',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: [],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Symbols',
    },
    {
        name: 'Noto Sans Symbols 2',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Brai'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Symbols 2',
    },
    {
        name: 'Noto Sans Syriac',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Syrc'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Syriac',
    },
    {
        name: 'Noto Sans Tagalog',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Tglg'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Tagalog',
    },
    {
        name: 'Noto Sans Tagbanwa',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Tagb'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Tagbanwa',
    },
    {
        name: 'Noto Sans Tai Le',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Tale'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Tai Le',
    },
    {
        name: 'Noto Sans Tai Tham',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Lana'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Tai Tham',
    },
    {
        name: 'Noto Sans Tai Viet',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Tavt'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Tai Viet',
    },
    {
        name: 'Noto Sans Takri',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Takr'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Takri',
    },
    {
        name: 'Noto Sans Tamil',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Taml'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Tamil',
    },
    {
        name: 'Noto Sans Tangsa',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Tnsa'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Tangsa',
    },
    {
        name: 'Noto Sans Telugu',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Telu'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Telugu',
    },
    {
        name: 'Noto Sans Thaana',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Thaa'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Thaana',
    },
    {
        name: 'Noto Sans Thai',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Thai'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Thai',
    },
    {
        name: 'Noto Sans Tifinagh',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Tfng'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Tifinagh',
    },
    {
        name: 'Noto Sans Tirhuta',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Tirh'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Tirhuta',
    },
    {
        name: 'Noto Sans Traditional Chinese',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Bopo', 'Hant'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Traditional Chinese',
    },
    {
        name: 'Noto Sans Ugaritic',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Ugar'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Ugaritic',
    },
    {
        name: 'Noto Sans Vai',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Vaii'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Vai',
    },
    {
        name: 'Noto Sans Wancho',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Wcho'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Wancho',
    },
    {
        name: 'Noto Sans Warang Citi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Wara'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Warang Citi',
    },
    {
        name: 'Noto Sans Yi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Yiii'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Yi',
    },
    {
        name: 'Noto Sans Zanabazar Square',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Zanb'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Sans Zanabazar Square',
    },
    {
        name: 'Noto Serif Ahom',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Ahom'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Serif Ahom',
    },
    {
        name: 'Noto Serif Dives Akuru',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Diak'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Serif Dives Akuru',
    },
    {
        name: 'Noto Serif Dogra',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Dogr'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Serif Dogra',
    },
    {
        name: 'Noto Serif Khitan Small Script',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Kits'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Serif Khitan Small Script',
    },
    {
        name: 'Noto Serif Makasar',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Maka'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Serif Makasar',
    },
    {
        name: 'Noto Serif NP Hmong',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Hmnp'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Serif NP Hmong',
    },
    {
        name: 'Noto Serif Old Uyghur',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Ougr'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Serif Old Uyghur',
    },
    {
        name: 'Noto Serif Tangut',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Tang'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Serif Tangut',
    },
    {
        name: 'Noto Serif Tibetan',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Tibt'],
        weights: { min: 100, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Noto Serif Tibetan',
    },
    {
        name: 'Noto Serif Todhri',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Todr'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Noto Serif Todhri',
    },
    {
        name: 'Noto Serif Toto',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Toto'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Serif Toto',
    },
    {
        name: 'Noto Serif Vithkuqi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Vith'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Serif Vithkuqi',
    },
    {
        name: 'Noto Serif Yezidi',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Yezi'],
        weights: { min: 400, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Serif Yezidi',
    },
    {
        name: 'Noto Traditional Nushu',
        roles: ['fallback'],
        delivery: 'preload',
        rangeSource: 'google',
        scripts: ['Nshu'],
        weights: { min: 300, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Noto Traditional Nushu',
    },
    {
        name: 'Pacifico',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn', 'Cyrl'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Pacifico',
    },
    {
        name: 'Papyrus',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'ttf',
        source: 'Papyrus',
    },
    {
        name: 'Passion One',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400, 700, 900],
        italic: false,
        format: 'woff2',
        source: 'Passion One',
    },
    {
        name: 'Permanent Marker',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Permanent Marker',
    },
    {
        name: 'Phudu',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: { min: 300, max: 900 },
        italic: false,
        format: 'woff2',
        source: 'Phudu',
    },
    {
        name: 'Play',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn', 'Cyrl', 'Grek'],
        weights: [400, 700],
        italic: false,
        format: 'woff2',
        source: 'Play',
    },
    {
        name: 'Poor Story',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Kore', 'Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Poor Story',
    },
    {
        name: 'Potta One',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Hira', 'Kana', 'Hani', 'Latn'],
        weights: [400],
        italic: false,
        format: 'ttf',
        source: 'Potta One',
    },
    {
        name: 'Quicksand',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: { min: 300, max: 700 },
        italic: false,
        format: 'woff2',
        source: 'Quicksand',
    },
    {
        name: 'Rampart One',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn', 'Hira', 'Kana', 'Hani'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Rampart One',
    },
    {
        name: 'Ribeye Marrow',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Ribeye Marrow',
    },
    {
        name: 'Roboto',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn', 'Cyrl', 'Grek'],
        weights: [100, 300, 400, 500, 700, 900],
        italic: true,
        format: 'woff2',
        source: 'Roboto',
    },
    {
        name: 'Shadows Into Light',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Shadows Into Light',
    },
    {
        name: 'Short Stack',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Short Stack',
    },
    {
        name: 'Silkscreen',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400, 700],
        italic: false,
        format: 'woff2',
        source: 'Silkscreen',
    },
    {
        name: 'Special Elite',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Special Elite',
    },
    {
        name: 'Stick',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Hira', 'Kana', 'Hani', 'Latn', 'Cyrl'],
        weights: [400],
        italic: false,
        format: 'ttf',
        source: 'Stick',
    },
    {
        name: 'Sue Ellen Francisco',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Sue Ellen Francisco',
    },
    {
        name: 'Tangerine',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400, 700],
        italic: false,
        format: 'woff2',
        source: 'Tangerine',
    },
    {
        name: 'Titan One',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn'],
        weights: [400],
        italic: false,
        format: 'woff2',
        source: 'Titan One',
    },
    {
        name: 'Ubuntu',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Latn', 'Cyrl', 'Grek'],
        weights: [300, 400, 500, 700],
        italic: true,
        format: 'woff2',
        source: 'Ubuntu',
    },
    {
        name: 'ZCOOL KuaiLe',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Hani', 'Hans'],
        weights: [400],
        italic: false,
        format: 'ttf',
        source: 'ZCOOL KuaiLe',
    },
    {
        name: 'ZCOOL QingKe HuangYou',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Hani', 'Hans'],
        weights: [400],
        italic: false,
        format: 'ttf',
        source: 'ZCOOL QingKe HuangYou',
    },
    {
        name: 'Zhi Mang Xing',
        roles: ['creator'],
        delivery: 'ondemand',
        rangeSource: 'preserve',
        scripts: ['Hani', 'Hans'],
        weights: [400],
        italic: false,
        format: 'ttf',
        source: 'Zhi Mang Xing',
    },
];
