/**
 * GENERATED by `npm run fonts-fix` from the shipped font files — do not edit by
 * hand. What each pickable face measures: `ratio` is x-height ÷ cap-height, and
 * `mono` is true when every letter is the same width. Read by the font build
 * into faces.generated.ts and said in words by faceWords.ts.
 *
 * Committed, unlike faces.generated.ts, because building it opens every creator
 * font file — the same reason renderable.generated.ts is committed.
 */
export const FaceMetrics: Record<string, { ratio?: number; mono?: boolean }> = {
    Aclonica: {
        ratio: 0.8,
    },
    Arvo: {
        ratio: 0.68,
    },
    'Berkshire Swash': {
        ratio: 0.56,
    },
    'Black Han Sans': {
        ratio: 0.8,
    },
    Borel: {
        ratio: 0.65,
    },
    'Bungee Outline': {
        ratio: 0.69,
    },
    'Cabin Sketch': {
        ratio: 0.77,
    },
    'Carter One': {
        ratio: 0.32,
    },
    Caveat: {
        ratio: 0.66,
    },
    Codystar: {
        ratio: 0.99,
    },
    'Comic Neue': {
        ratio: 0.73,
    },
    'Courier Prime': {
        ratio: 0.78,
        mono: true,
    },
    'Crafty Girls': {
        ratio: 0.71,
    },
    Creepster: {
        ratio: 1,
    },
    Delius: {
        ratio: 0.44,
    },
    'Dot Gothic 16': {
        ratio: 0.69,
    },
    Doto: {
        ratio: 0.71,
        mono: true,
    },
    'Dreaming Outloud': {
        ratio: 0.67,
    },
    Gorditas: {
        ratio: 0.72,
    },
    Graduate: {
        ratio: 0.87,
    },
    'Hi Melody': {
        ratio: 0.63,
    },
    'Luckiest Guy': {
        ratio: 0.98,
    },
    Megrim: {
        ratio: 0.83,
    },
    Merriweather: {
        ratio: 0.75,
    },
    Modak: {
        ratio: 0.85,
    },
    'Modern Love': {
        ratio: 0.62,
    },
    Monoton: {
        ratio: 0.87,
    },
    'Mouse Memoirs': {
        ratio: 0.72,
    },
    'Noto Sans': {
        ratio: 0.75,
    },
    'Noto Sans Japanese': {
        ratio: 0.74,
    },
    'Noto Sans Korean': {
        ratio: 0.74,
    },
    'Noto Sans Mono': {
        ratio: 0.75,
    },
    'Noto Sans Simplified Chinese': {
        ratio: 0.74,
    },
    Pacifico: {
        ratio: 0.55,
    },
    'Passion One': {
        ratio: 0.77,
    },
    'Permanent Marker': {
        ratio: 0.82,
    },
    Phudu: {
        ratio: 0.71,
    },
    Play: {
        ratio: 0.75,
    },
    'Poor Story': {
        ratio: 0.61,
    },
    'Potta One': {
        ratio: 0.72,
    },
    Quicksand: {
        ratio: 0.72,
    },
    'Rampart One': {
        ratio: 0.73,
    },
    'Ribeye Marrow': {
        ratio: 0.73,
    },
    Roboto: {
        ratio: 0.74,
    },
    'Shadows Into Light': {
        ratio: 0.95,
    },
    'Short Stack': {
        ratio: 0.55,
    },
    Silkscreen: {
        ratio: 0.71,
    },
    'Special Elite': {
        ratio: 0.74,
    },
    Stick: {
        ratio: 0.73,
    },
    'Sue Ellen Francisco': {
        ratio: 0.4,
    },
    Tangerine: {
        ratio: 0.4,
    },
    'Titan One': {
        ratio: 0.82,
    },
    Ubuntu: {
        ratio: 0.75,
    },
    'ZCOOL KuaiLe': {
        ratio: 0.73,
    },
    'ZCOOL QingKe HuangYou': {
        ratio: 0.68,
    },
    'Zhi Mang Xing': {
        ratio: 0.66,
    },
};
