name: Defect
description: Report something not working as intended.
labels: ['defect', 'needs triage']
type: 'defect'
projects: ['wordplaydev/7']
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this defect report!
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          placeholder: What happened?
          description: |
              Provide list of steps that consistently reproduce the behavior, including any example code.
              1. In this environment...
              1. With this config...
              1. Run '...'
              1. See error...

              Make the steps as minimal as possible, finding the smallest possible set of steps that still produce the unexpected behavior. What is the defect and what did you expect to happen instead?
      validations:
          required: true
    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Any links, references, or other context that would help, or guesses about what might be causing it? You can attach images or log files by clicking this area to highlight it and then dragging files in.
    - type: dropdown
      id: browsers
      attributes:
          label: What browsers are you seeing the problem on?
          description: |
              If the problem is on multiple browsers, reopen the dropdown and choose each one individually.
          multiple: true
          options:
              - Firefox
              - Chrome
              - Safari
              - Microsoft Edge
      validations:
          required: true
    - type: dropdown
      id: os
      attributes:
          label: What operating system are you using?
          multiple: true
          options:
              - Windows
              - macOS
              - Linux
      validations:
          required: true
