export enum SemanticConflict {
    EXPECTED_BLOCK_EXPRESSION,
    EXPECTED_BLOCK_LAST_EXPRESSION,
    IGNORED_BLOCK_EXPRESSION,
    BIND_ALIASES_ARENT_UNIQUE,
    SHARE_NOT_ALLOWED,
    SHARING_REQUIRES_LANGUAGES,
    UNDEFINED_NAME
}