import * as fs from 'node:fs';
import { deriveEmojiRange, EMOJI_WHOLE_FILE } from './deriveRange';
import {
    buildLockfile,
    writeLock,
    readLock,
    baseFallbackCoverage,
} from './lockfile';
import type { Lockfile } from './lockfile';
import { buildFaces, buildFallback } from './faces';
import type { FaceRecord } from './faces';
import { emitFontsCss, emitFontsFallbackCss } from './stylesheets';
import { writeRenderableGenerated } from './renderableSet';
import { FontManifest } from '../../src/basis/faces/fonts.manifest';

/** Scripts present in the glyph data with no released Noto font. Captured from
 * the manifest's coverage; the coverage-partition test keeps it honest. */
const UNCOVERED_SCRIPTS = [
    'Berf',
    'Gara',
    'Gukh',
    'Krai',
    'Onao',
    'Sidt',
    'Tayo',
    'Tols',
    'Tutg',
];

const GENERATED = 'src/basis/faces/faces.generated.ts';
const FALLBACK_GENERATED = 'src/basis/faces/faces.fallback.generated.ts';

function fmtWeights(w: FaceRecord['weights']): string {
    return Array.isArray(w)
        ? `[${w.join(', ')}]`
        : `{ min: ${w.min}, max: ${w.max} }`;
}

function fmtRanges(r: string | string[] | undefined): string | undefined {
    if (r === undefined) return undefined;
    return Array.isArray(r)
        ? `[\n${r.map((s) => `            ${JSON.stringify(s)},`).join('\n')}\n        ]`
        : JSON.stringify(r);
}

function emitFace(name: string, face: FaceRecord): string {
    const lines = [
        `    ${JSON.stringify(name)}: {`,
        `        weights: ${fmtWeights(face.weights)},`,
        `        italic: ${face.italic},`,
        `        scripts: [${face.scripts.map((s) => `'${s}'`).join(', ')}],`,
        `        format: '${face.format}',`,
    ];
    if (face.preloaded) lines.push(`        preloaded: true,`);
    const ranges = fmtRanges(face.ranges);
    if (ranges !== undefined) lines.push(`        ranges: ${ranges},`);
    lines.push(`    },`);
    return lines.join('\n');
}

/** Compute the emoji faces' cmap-derived ranges (rangeSource 'emoji'). */
export async function emojiRanges(): Promise<Record<string, string>> {
    const out: Record<string, string> = {};
    for (const entry of FontManifest)
        if (entry.rangeSource === 'emoji')
            out[entry.name] = await deriveEmojiRange(
                EMOJI_WHOLE_FILE[entry.name],
            );
    return out;
}

/** Regenerate faces.generated.ts (the RUNTIME registry) from the manifest +
 * lockfile: the creator `Faces` (pickable in the font chooser, whose ranges the
 * runtime uses to register FontFaces) plus `FallbackFaceNames` — the fallback
 * font-family names in cascade order, the ONLY fallback data the runtime reads
 * (via FallbackFontFamilies). The full structured fallback table (scripts,
 * weights, unicode-ranges) is emitted separately to faces.fallback.generated.ts
 * for tests only; shipping its ~145 KB of range data would just duplicate
 * static/fonts/fonts-fallback.css, which is what actually drives fallback glyph
 * loading. */
export async function emitFacesGenerated(lock: Lockfile): Promise<string> {
    const faces = buildFaces(lock, await emojiRanges());
    const fallback = buildFallback(lock);

    const facesBody = Object.entries(faces)
        .map(([name, face]) => emitFace(name, face))
        .join('\n');

    const namesBody = fallback
        .map((f) => `    ${JSON.stringify(f.name)},`)
        .join('\n');

    return `/**
 * GENERATED by \`npm run fonts-fix\` from fonts.manifest.ts + fonts.lock.json —
 * do not edit by hand. The RUNTIME face registry: the creator Faces (pickable
 * in the font chooser) and FallbackFaceNames (the fallback family cascade). The
 * structured FallbackFaces table (scripts/weights/ranges) lives in
 * faces.fallback.generated.ts and is imported only by tests — the runtime never
 * reads those fields (fallback glyph loading is driven by fonts-fallback.css).
 */
import type { Face } from './Fonts';

export const Faces: Record<string, Face> = {
${facesBody}
};

/** Fallback font-family names, in cascade order — mirrors the
 * --wordplay-fallback-fonts custom property in static/fonts/fonts-fallback.css.
 * The only fallback data the runtime uses (see FallbackFontFamilies). */
export const FallbackFaceNames: readonly string[] = [
${namesBody}
];
`;
}

/** Regenerate faces.fallback.generated.ts — the TEST-ONLY structured fallback
 * table (name/scripts/weights/unicode-ranges) plus UncoveredScripts. Imported
 * only by the font tests (FallbackFonts.test.ts, fontsSync.test.ts) and the
 * fonts CLI (start.ts) to verify font files exist and ranges cover expected
 * codepoints. Kept out of the runtime bundle — the runtime uses only the name
 * list in faces.generated.ts. */
export function emitFallbackGenerated(lock: Lockfile): string {
    const fallbackBody = buildFallback(lock)
        .map((f) =>
            [
                '    {',
                `        name: ${JSON.stringify(f.name)},`,
                `        scripts: [${f.scripts.map((s) => `'${s}'`).join(', ')}],`,
                `        weights: ${fmtWeights(f.weights)},`,
                '        ranges: [',
                ...f.ranges.map((r) => `            ${JSON.stringify(r)},`),
                '        ],',
                '    },',
            ].join('\n'),
        )
        .join('\n');

    return `/**
 * GENERATED by \`npm run fonts-fix\` from fonts.manifest.ts + fonts.lock.json —
 * do not edit by hand. TEST-ONLY: the full structured fallback face table and
 * UncoveredScripts. The runtime does not import this (it uses FallbackFaceNames
 * in faces.generated.ts); these unicode-ranges duplicate fonts-fallback.css and
 * exist only so the font tests can verify file existence + range coverage.
 */
import type { Script } from '@locale/Scripts';

export type FallbackFace = {
    readonly name: string;
    readonly scripts: readonly Script[];
    readonly weights: import('./Fonts').FontWeightRange | readonly import('./Fonts').FontWeight[];
    readonly ranges: readonly string[];
};

export const FallbackFaces: readonly FallbackFace[] = [
${fallbackBody}
];

export const UncoveredScripts: readonly Script[] = [
${UNCOVERED_SCRIPTS.map((s) => `    '${s}',`).join('\n')}
];
`;
}

/** Fast build step for postinstall/CI: re-emit the cheap artifacts
 * (faces.generated.ts + both stylesheets) from the COMMITTED lockfile. The only
 * cmap reads are the two small emoji fonts and Noto Sans's 400 slices (for the
 * fallback base coverage) — cheap enough to keep in every build. Used to keep
 * these files out of the repo while still present in every build.
 * renderable.generated.ts is committed (its cmap-union is expensive) and left
 * untouched here. */
export async function build(): Promise<void> {
    const lock = readLock();
    fs.writeFileSync(GENERATED, await emitFacesGenerated(lock));
    fs.writeFileSync(FALLBACK_GENERATED, emitFallbackGenerated(lock));
    fs.writeFileSync('static/fonts/fonts.css', emitFontsCss(lock));
    fs.writeFileSync(
        'static/fonts/fonts-fallback.css',
        emitFontsFallbackCss(lock, await baseFallbackCoverage()),
    );
}

/** Full regeneration for humans: rebuild the lockfile (cmap for changed
 * whole-file faces), re-emit every artifact including the expensive renderable
 * set, and update the committed lockfile. The caller runs prettier. */
export async function fix(): Promise<void> {
    const lock = await buildLockfile(readLock(), true);
    writeLock(lock);
    await build();
    await writeRenderableGenerated();
    console.log(
        `Regenerated the lockfile, faces.generated.ts, both stylesheets, and renderable.generated.ts.`,
    );
}
