import * as fs from 'node:fs';
import * as path from 'node:path';
import { FontManifest } from '../../src/basis/faces/fonts.manifest';
import { spaceless } from './files';

/**
 * The measured half of a face's description: how tall its lowercase sits, and
 * whether every letter is the same width.
 *
 * Committed rather than rebuilt on every build, for the reason
 * renderable.generated.ts is: computing it opens every creator font file, and
 * `build()` deliberately keeps its cmap reads down to two emoji fonts. So this
 * is regenerated by `npm run fonts-fix`, checked into the repo, and read by
 * buildFaces the way the lockfile's ranges are.
 */

export const METRICS_PATH = 'src/basis/faces/metrics.generated.ts';

export type FaceMetrics = { ratio?: number; mono?: boolean };

/**
 * Measure one face.
 *
 * Two things make this less obvious than it looks. The shipped files are
 * unicode-range *slices*, so the first one alphabetically often has no Latin at
 * all and reports glyph 0 for both `a` and `A` — hence the search for a file
 * that actually has lowercase before trusting any number from it. And a face
 * with no `xHeight` or `capHeight` (some CJK and emoji faces) simply gets no
 * ratio rather than a made-up one.
 */
async function measure(name: string): Promise<FaceMetrics | undefined> {
    const dir = path.join('static/fonts', spaceless(name));
    if (!fs.existsSync(dir)) return undefined;
    const files = fs
        .readdirSync(dir)
        .filter((f) => /\.(woff2|ttf|otf)$/.test(f))
        .sort();
    const mod = await import('fontkit');
    const fontkit: { create(data: Uint8Array): unknown } =
        'create' in mod
            ? (mod as { create(data: Uint8Array): unknown })
            : (mod as { default: { create(data: Uint8Array): unknown } })
                  .default;
    let fallback: FaceMetrics | undefined = undefined;
    for (const file of files) {
        let font;
        try {
            const created = fontkit.create(
                new Uint8Array(fs.readFileSync(path.join(dir, file))),
            );
            font =
                created !== null &&
                typeof created === 'object' &&
                'fonts' in created
                    ? (created as { fonts: unknown[] }).fonts[0]
                    : created;
        } catch {
            continue;
        }
        const f = font as {
            xHeight?: number;
            capHeight?: number;
            post?: { isFixedPitch?: number | boolean };
            glyphForCodePoint(cp: number): { id: number };
        };
        const metrics: FaceMetrics = {};
        if (f.xHeight && f.capHeight)
            metrics.ratio = Math.round((f.xHeight / f.capHeight) * 100) / 100;
        if (f.post?.isFixedPitch) metrics.mono = true;
        // Only trust a ratio read from a slice that actually carries lowercase.
        let hasLatin = false;
        try {
            hasLatin = f.glyphForCodePoint(0x61).id !== 0;
        } catch {
            hasLatin = false;
        }
        if (hasLatin) return metrics;
        // A slice with no lowercase can still say whether the face is
        // monospaced, but its x-height is meaningless — drop just the ratio.
        if (fallback === undefined)
            fallback = metrics.mono ? { mono: true } : {};
    }
    return fallback;
}

/** Measure every face a creator can pick. */
export async function buildMetrics(): Promise<Record<string, FaceMetrics>> {
    const out: Record<string, FaceMetrics> = {};
    for (const entry of FontManifest) {
        if (!entry.roles.includes('creator')) continue;
        const metrics = await measure(entry.name);
        if (metrics === undefined) continue;
        const kept: FaceMetrics = {};
        if (metrics.ratio !== undefined) kept.ratio = metrics.ratio;
        if (metrics.mono) kept.mono = true;
        if (Object.keys(kept).length > 0) out[entry.name] = kept;
    }
    return out;
}

/** Read the committed metrics. Imported rather than parsed out of the file:
 *  it's committed, so it always exists even on a fresh clone, and importing it
 *  can't drift from however the emitter happens to format it. */
export async function readMetrics(): Promise<Record<string, FaceMetrics>> {
    if (!fs.existsSync(METRICS_PATH)) return {};
    const mod = await import('../../src/basis/faces/metrics.generated');
    return mod.FaceMetrics;
}

export function emitMetrics(metrics: Record<string, FaceMetrics>): string {
    const sorted: Record<string, FaceMetrics> = {};
    for (const key of Object.keys(metrics).sort()) sorted[key] = metrics[key];
    return `/**
 * GENERATED by \`npm run fonts-fix\` from the shipped font files — do not edit by
 * hand. What each pickable face measures: \`ratio\` is x-height ÷ cap-height, and
 * \`mono\` is true when every letter is the same width. Read by the font build
 * into faces.generated.ts and said in words by faceWords.ts.
 *
 * Committed, unlike faces.generated.ts, because building it opens every creator
 * font file — the same reason renderable.generated.ts is committed.
 */
export const FaceMetrics: Record<string, { ratio?: number; mono?: boolean }> =
    ${JSON.stringify(sorted, null, 4)};
`;
}

export async function writeMetrics(): Promise<void> {
    fs.writeFileSync(METRICS_PATH, emitMetrics(await buildMetrics()));
}
