import * as path from 'node:path';
import { readCharacterSet } from './deriveRange';
import type { Interval } from './deriveRange';
import { entryFiles } from './lockfile';
import { EMOJI_WHOLE_FILE } from './deriveRange';
import { FontManifest } from '../../src/basis/faces/fonts.manifest';

/**
 * The set of codepoints some default-chain font can actually draw — the union
 * of every chain face's real cmap. The glyph chooser filters against this so
 * it never offers a codepoint that would render as tofu.
 *
 * This must use cmaps, not declared unicode-ranges: Google's slice partitions
 * declare whole blocks (e.g. all of Arabic Presentation Forms) while the file
 * lacks glyphs for the unassigned/rare codepoints in them, so a declared-range
 * check over-reports renderability.
 *
 * "Chain" = the faces used to render by default: the preloaded faces (Noto
 * Sans/Mono, emoji) and every fallback face. Decorative on-demand creator
 * faces are excluded — a glyph only they contain would tofu in default output.
 */

const GENERATED = 'src/basis/faces/renderable.generated.ts';

export async function computeRenderableRanges(): Promise<Interval[]> {
    const files = new Set<string>();
    for (const entry of FontManifest) {
        if (entry.delivery !== 'preload' && !entry.roles.includes('fallback'))
            continue;
        for (const url of entryFiles(entry))
            files.add(path.join('static', url));
    }
    // The Safari SVG emoji face is a .ttf outside the woff2 file listing.
    for (const whole of Object.values(EMOJI_WHOLE_FILE)) files.add(whole);

    const covered = new Set<number>();
    for (const file of files)
        for (const cp of await readCharacterSet(file)) covered.add(cp);

    const sorted = [...covered].sort((a, b) => a - b);
    const intervals: Interval[] = [];
    for (const cp of sorted) {
        const last = intervals[intervals.length - 1];
        if (last && cp <= last[1] + 1) last[1] = cp;
        else intervals.push([cp, cp]);
    }
    return intervals;
}

export function emitRenderableGenerated(intervals: Interval[]): string {
    const body = intervals
        .map(([a, b]) => `    [0x${a.toString(16)}, 0x${b.toString(16)}],`)
        .join('\n');
    return `/**
 * GENERATED by \`npm run fonts-fix\` — do not edit by hand. The merged
 * [lo, hi] codepoint intervals some default-chain font actually has a glyph
 * for (the union of every chain face's cmap). isCodepointRenderable
 * (renderable.ts) binary-searches this so the glyph chooser never offers a
 * codepoint that would render as tofu.
 */
export const RenderableRanges: readonly (readonly [number, number])[] = [
${body}
];
`;
}

export async function writeRenderableGenerated(): Promise<void> {
    const { default: fs } = await import('node:fs');
    fs.writeFileSync(
        GENERATED,
        emitRenderableGenerated(await computeRenderableRanges()),
    );
}
