import * as fs from 'node:fs';
import { parseFontUrl } from './files';
import { entryFiles } from './lockfile';
import type { Lockfile } from './lockfile';
import { buildFallback } from './faces';
import { FontManifest } from '../../src/basis/faces/fonts.manifest';
import type { FontManifestEntry } from '../../src/basis/faces/fonts.manifest';

/**
 * Emits the two stylesheets from the manifest + lockfile. Mechanical faces
 * (Noto Sans/Mono, all fallbacks) are generated @font-face by @font-face;
 * bespoke faces (emoji) inline their hand-authored css partial via the
 * manifest `override`. Output is prettier-formatted by the caller, so this
 * only needs to be semantically correct, not pretty.
 */

const PARTIAL_DIR = 'src/basis/faces';

const format = (url: string) =>
    url.endsWith('.woff2')
        ? 'woff2'
        : url.endsWith('.otf')
          ? 'opentype'
          : 'truetype';

/** One @font-face rule for a served slice file. */
function fontFace(
    entry: FontManifestEntry,
    url: string,
    range: string,
): string {
    const { weight, italic } = parseFontUrl(`/${url}`);
    // 'all' means a variable file; use the face's weight axis from the manifest.
    const weightCss =
        weight === 'all' && 'min' in entry.weights
            ? `${entry.weights.min} ${entry.weights.max}`
            : weight;
    return [
        '@font-face {',
        `    font-family: '${entry.name}';`,
        `    font-style: ${italic ? 'italic' : 'normal'};`,
        `    font-weight: ${weightCss};`,
        `    font-display: swap;`,
        `    src: url(/${url}) format('${format(url)}');`,
        `    unicode-range: ${range};`,
        '}',
    ].join('\n');
}

/** All mechanical @font-face rules for one face (skips override faces). */
function mechanicalFace(entry: FontManifestEntry, lock: Lockfile): string {
    const rules: string[] = [];
    for (const url of entryFiles(entry)) {
        const range = lock[url]?.range;
        if (range == null) continue; // whole-file faces w/o a declared range aren't in CSS
        rules.push(fontFace(entry, url, range));
    }
    return rules.join('\n');
}

export function emitFontsCss(lock: Lockfile): string {
    const header = `/*
 * GENERATED by \`npm run fonts-fix\` from fonts.manifest.ts + fonts.lock.json.
 * Do not edit by hand. Declares the preloaded faces (Noto Sans, Noto Sans Mono)
 * and the emoji faces. The emoji section is a hand-authored island
 * (emoji-faces.css) inlined via the manifest \`override\`; its ranges are
 * cmap-guarded by the drift test. The lazy per-script fallback faces live in
 * the sibling fonts-fallback.css.
 */\n`;

    // Preloaded non-fallback, non-emoji faces (Noto Sans, Noto Sans Mono).
    // Fallback faces — including the dual-role CJK ones — live in
    // fonts-fallback.css, not here.
    const preload = FontManifest.filter(
        (e) =>
            e.delivery === 'preload' &&
            !e.roles.includes('fallback') &&
            e.rangeSource !== 'emoji' &&
            e.override === undefined,
    )
        .map((e) => mechanicalFace(e, lock))
        .filter((s) => s.length > 0);

    // The emoji island(s): inline each override partial targeting fonts.css.
    const partials = FontManifest.filter(
        (e) => e.override?.target === 'fonts.css',
    )
        .map((e) =>
            fs
                .readFileSync(
                    `${PARTIAL_DIR}/${e.override!.cssPartial}`,
                    'utf8',
                )
                .trimEnd(),
        )
        .join('\n\n');

    return `${header}\n${preload.join('\n')}\n\n${partials}\n`;
}

export function emitFontsFallbackCss(lock: Lockfile): string {
    const header = `/*
 * GENERATED by \`npm run fonts-fix\` from fonts.manifest.ts + fonts.lock.json.
 * Do not edit by hand. Declares every Noto fallback face with unicode-range so
 * browsers lazily download only the slices needed by rendered text, and defines
 * --wordplay-fallback-fonts, the family list appended to every font-family
 * chain. All fonts are licensed under the SIL OFL 1.1 (see /fonts/OFL.txt).
 */\n`;

    // Chain order comes from buildFallback (script → symbol → CJK).
    const ordered = buildFallback(lock);
    const byName = new Map(FontManifest.map((e) => [e.name, e]));
    const blocks = ordered
        .map((f) => mechanicalFace(byName.get(f.name)!, lock))
        .join('\n');

    const varValue = ordered.map((f) => `'${f.name}'`).join(', ');
    return `${header}\n${blocks}\n\n:root {\n    --wordplay-fallback-fonts: ${varValue};\n}\n`;
}
