import * as fs from 'node:fs';
import { parseFontUrl } from './files';
import { entryFiles } from './lockfile';
import type { Lockfile } from './lockfile';
import { buildFallback } from './faces';
import { parseRangeString, toRangeString } from './deriveRange';
import { FontManifest } from '../../src/basis/faces/fonts.manifest';
import type { FontManifestEntry } from '../../src/basis/faces/fonts.manifest';

/**
 * Emits the two stylesheets from the manifest + lockfile. Mechanical faces
 * (Noto Sans/Mono, all fallbacks) are generated @font-face by @font-face;
 * bespoke faces (emoji) inline their hand-authored css partial via the
 * manifest `override`. Output is prettier-formatted by the caller, so this
 * only needs to be semantically correct, not pretty.
 */

const PARTIAL_DIR = 'src/basis/faces';

const format = (url: string) =>
    url.endsWith('.woff2')
        ? 'woff2'
        : url.endsWith('.otf')
          ? 'opentype'
          : 'truetype';

/** One @font-face rule for a served slice file. */
function fontFace(
    entry: FontManifestEntry,
    url: string,
    range: string,
): string {
    const { weight, italic } = parseFontUrl(`/${url}`);
    // 'all' means a variable file; use the face's weight axis from the manifest.
    const weightCss =
        weight === 'all' && 'min' in entry.weights
            ? `${entry.weights.min} ${entry.weights.max}`
            : weight;
    return [
        '@font-face {',
        `    font-family: '${entry.name}';`,
        `    font-style: ${italic ? 'italic' : 'normal'};`,
        `    font-weight: ${weightCss};`,
        `    font-display: swap;`,
        `    src: url(/${url}) format('${format(url)}');`,
        `    unicode-range: ${range};`,
        '}',
    ].join('\n');
}

/** All mechanical @font-face rules for one face (skips override faces).
 *
 * `ranges`, when given (the lazy fallback faces), replaces each slice's declared
 * range with its de-duplicated range (see computeFallbackRanges); a slice left
 * empty is omitted. Without it (the preloaded faces) the lockfile range is used
 * verbatim. */
function mechanicalFace(
    entry: FontManifestEntry,
    lock: Lockfile,
    ranges?: ReadonlyMap<string, string>,
): string {
    const rules: string[] = [];
    for (const url of entryFiles(entry)) {
        const range = ranges ? ranges.get(url) : lock[url]?.range;
        if (range == null || range === '') continue; // no glyphs to declare here
        rules.push(fontFace(entry, url, range));
    }
    return rules.join('\n');
}

/** The de-duplicated unicode-range for every served fallback slice file.
 *
 * Google slices a shared Latin/punctuation/symbol range into ALL ~150 Noto
 * fallback faces, so rendering a single shared glyph (an arrow, a special space,
 * a dagger…) would download every one of them at once. This assigns each
 * codepoint to exactly ONE face: starting from `baseCoverage` (what the
 * preloaded Noto Sans already renders, stripped from every fallback), each face
 * — symbol/math faces first, so shared symbols attribute to Noto Sans Symbols
 * rather than a random script font — claims only the codepoints not already
 * claimed by an earlier face. So a shared glyph now downloads one font, and each
 * script glyph still downloads only its script's face. No tofu: every codepoint
 * is still declared by exactly one face (base coverage by Noto Sans). */
export function computeFallbackRanges(
    lock: Lockfile,
    baseCoverage: ReadonlySet<number>,
): Map<string, string> {
    const ordered = buildFallback(lock);
    const byName = new Map(FontManifest.map((e) => [e.name, e]));
    // Claim order: symbol/math faces (no scripts) first, then the chain order.
    const priority = [
        ...ordered.filter((f) => f.scripts.length === 0),
        ...ordered.filter((f) => f.scripts.length > 0),
    ];
    const claimed = new Set<number>(baseCoverage);
    const result = new Map<string, string>();
    for (const face of priority) {
        const entry = byName.get(face.name);
        if (entry === undefined) continue;
        const faceCps: number[] = [];
        for (const url of entryFiles(entry)) {
            const range = lock[url]?.range;
            if (range == null) continue;
            const kept = parseRangeString(range).filter(
                (cp) => !claimed.has(cp),
            );
            result.set(url, toRangeString(kept));
            faceCps.push(...kept);
        }
        // Claim after the whole face so its own slices don't shadow each other.
        for (const cp of faceCps) claimed.add(cp);
    }
    return result;
}

export function emitFontsCss(lock: Lockfile): string {
    const header = `/*
 * GENERATED by \`npm run fonts-fix\` from fonts.manifest.ts + fonts.lock.json.
 * Do not edit by hand. Declares the preloaded faces (Noto Sans, Noto Sans Mono)
 * and the emoji faces. The emoji section is a hand-authored island
 * (emoji-faces.css) inlined via the manifest \`override\`; its ranges are
 * cmap-guarded by the drift test. The lazy per-script fallback faces live in
 * the sibling fonts-fallback.css.
 */\n`;

    // Preloaded non-fallback, non-emoji faces (Noto Sans, Noto Sans Mono).
    // Fallback faces — including the dual-role CJK ones — live in
    // fonts-fallback.css, not here.
    const preload = FontManifest.filter(
        (e) =>
            e.delivery === 'preload' &&
            !e.roles.includes('fallback') &&
            e.rangeSource !== 'emoji' &&
            e.override === undefined,
    )
        .map((e) => mechanicalFace(e, lock))
        .filter((s) => s.length > 0);

    // The emoji island(s): inline each override partial targeting fonts.css.
    const partials = FontManifest.filter(
        (e) => e.override?.target === 'fonts.css',
    )
        .map((e) =>
            fs
                .readFileSync(
                    `${PARTIAL_DIR}/${e.override!.cssPartial}`,
                    'utf8',
                )
                .trimEnd(),
        )
        .join('\n\n');

    return `${header}\n${preload.join('\n')}\n\n${partials}\n`;
}

export function emitFontsFallbackCss(
    lock: Lockfile,
    baseCoverage: ReadonlySet<number>,
): string {
    const header = `/*
 * GENERATED by \`npm run fonts-fix\` from fonts.manifest.ts + fonts.lock.json.
 * Do not edit by hand. Declares every Noto fallback face with unicode-range so
 * browsers lazily download only the slices needed by rendered text, and defines
 * --wordplay-fallback-fonts, the family list appended to every font-family
 * chain. Each codepoint is declared by exactly one face (see
 * computeFallbackRanges) so a shared glyph downloads one font, not all ~150.
 * All fonts are licensed under the SIL OFL 1.1 (see /fonts/OFL.txt).
 */\n`;

    // Chain order comes from buildFallback (script → symbol → CJK); the ranges
    // are de-duplicated so each glyph lives on exactly one face.
    const ranges = computeFallbackRanges(lock, baseCoverage);
    const ordered = buildFallback(lock);
    const byName = new Map(FontManifest.map((e) => [e.name, e]));
    const blocks = ordered
        .map((f) => {
            const entry = byName.get(f.name);
            return entry ? mechanicalFace(entry, lock, ranges) : '';
        })
        .join('\n');

    const varValue = ordered.map((f) => `'${f.name}'`).join(', ');
    return `${header}\n${blocks}\n\n:root {\n    --wordplay-fallback-fonts: ${varValue};\n}\n`;
}
