import { readFileSync } from 'fs';
import { resolve } from 'path';
import { ConditionCodes, SeasonCodes } from '#seasons/seasonCodes.ts';
import { calendar, classify } from './classify.ts';
import { isNormalsFile, NormalsPath, type NormalsFile } from './normals.ts';

export const ZoneTablePath = resolve(
    import.meta.dirname,
    '../../src/seasons/zoneSeasons.generated.ts',
);

export function readNormals(): NormalsFile {
    const parsed: unknown = JSON.parse(readFileSync(NormalsPath, 'utf-8'));
    if (!isNormalsFile(parsed)) throw new Error(`Unreadable ${NormalsPath}`);
    return parsed;
}

/** The generated zone table's source text, a function of normals.json alone. */
export function toZoneTable(file: NormalsFile): string {
    const zones = Object.keys(file.zones).sort();
    const rows = zones.flatMap((zone) => {
        const entry = file.zones[zone];
        if (entry === undefined) return [];
        const { koppen } = classify(entry.normals, entry.lat);
        const months = calendar(entry.normals, entry.lat)
            .map(
                ({ season, condition }) =>
                    SeasonCodes[season] + ConditionCodes[condition],
            )
            .join('');
        return [
            `    ${JSON.stringify(zone)}: [${JSON.stringify(entry.country)}, ${JSON.stringify(koppen)}, ${JSON.stringify(months)}],`,
        ];
    });
    const aliases = Object.keys(file.aliases)
        .sort()
        .flatMap((alias) => {
            const target = file.aliases[alias];
            return target !== undefined &&
                target in file.zones &&
                !(alias in file.zones)
                ? [`    ${JSON.stringify(alias)}: ${JSON.stringify(target)},`]
                : [];
        });
    return [
        '// Generated by `npm run seasons-build` from scripts/seasons/normals.json',
        '// (scripts/seasons/zoneTable.ts). Never hand-edit; seasonsSync.test.ts fails on drift.',
        '',
        '/** Each IANA zone: its country, Köppen-Geiger class, and twelve months of',
        ' *  season and condition codes (seasonCodes.ts), January first. */',
        'export const ZoneSeasons: Record<string, readonly [string, string, string]> = {',
        ...rows,
        '};',
        '',
        '/** Legacy zone names some browsers still report, and the zone each names. */',
        'export const ZoneAliases: Record<string, string> = {',
        ...aliases,
        '};',
        '',
    ].join('\n');
}
