import { mkdirSync, writeFileSync } from 'fs';
import { format } from 'prettier';
import { dirname, join, resolve } from 'path';
import { fileURLToPath } from 'url';
import {
    Emails,
    renderSample,
    type EmailKind,
} from '../../functions/src/email/registry';

/**
 * Every email Wordplay sends, on one page.
 *
 * Two outputs, deliberately split. The HTML sheet is a preview — it renders
 * each message in a light and a dark frame so a person can look at them
 * together — and it is gitignored, because committing a blob that regenerates
 * on every copy edit is churn. The Markdown sheet is the durable half: who each
 * email goes to, from what address, whether it is localized, and whether it can
 * be turned off. That one is committed and drift-tested, the way the
 * contributors list is.
 *
 * Imports the registry directly, which a root script may do — but only because
 * the registry never reaches `send.ts`. See `emailImports.test.ts`.
 */

const Root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

// Render the links a creator actually receives. `canonicalOrigin()` resolves
// from GCLOUD_PROJECT, which is unset locally — so without this the sheet shows
// test.wordplay.dev and misrepresents every link on it.
process.env.GCLOUD_PROJECT = 'wordplay-prod';
delete process.env.FUNCTIONS_EMULATOR;
const HtmlOut = join(Root, 'build/emails/index.html');
const MarkdownOut = join(Root, 'EMAILS.md');

function escape(text: string): string {
    return text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

async function sheetHTML(
    rendered: { kind: EmailKind; subject: string; html: string }[],
): Promise<string> {
    const cards = rendered
        .map(({ kind, subject, html }) => {
            // Each message goes in an iframe so its own styles, and its own
            // dark-mode rules, apply as a client would apply them. The pair of
            // frames is why this sheet exists: the palette has two answers.
            const frame = (scheme: 'light' | 'dark') =>
                `<div class="frame ${scheme}"><div class="frame-label">${scheme}</div><iframe title="${escape(kind.id)} in ${scheme}" style="color-scheme:${scheme}" srcdoc="${escape(html)}"></iframe></div>`;
            return `<section>
<h2>${escape(kind.id)}</h2>
<p class="what">${escape(kind.what)}</p>
<dl>
<dt>Subject</dt><dd>${escape(subject)}</dd>
<dt>Sent when</dt><dd>${escape(kind.trigger)}</dd>
<dt>To</dt><dd>${escape(kind.to)}</dd>
<dt>From</dt><dd>${escape(kind.from)}</dd>
<dt>Reply to</dt><dd>${escape(kind.replyTo)}</dd>
<dt>Translated</dt><dd>${kind.localized ? 'yes' : 'no'}</dd>
<dt>Optional</dt><dd>${escape(kind.optional)}</dd>
</dl>
<div class="frames">${frame('light')}${frame('dark')}</div>
</section>`;
        })
        .join('\n');

    return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<title>Wordplay emails</title>
<style>
:root { color-scheme: light dark; }
body { font-family: 'Noto Sans', system-ui, sans-serif; margin: 0; padding: 2rem; line-height: 1.5; }
h1 { transform: rotate(-1deg); }
section { margin-block-end: 3rem; border-top: 1px solid #9f9f9f; padding-top: 1rem; }
h2 { transform: rotate(-1deg); font-family: 'Noto Sans Mono', monospace; }
.what { max-width: 40em; }
dl { display: grid; grid-template-columns: max-content 1fr; gap: 0.25rem 1rem; max-width: 60em; }
dt { color: #6b6b6b; }
dd { margin: 0; }
.frames { display: flex; flex-wrap: wrap; gap: 1rem; margin-block-start: 1rem; }
.frame { border: 1px solid #9f9f9f; border-radius: 8px; overflow: hidden; }
.frame-label { font-size: 10pt; padding: 0.25rem 0.5rem; color: #6b6b6b; }
.light { background: #ffffff; }
.dark { background: #000000; }
iframe { width: 640px; height: 520px; border: none; display: block; }
</style></head>
<body>
<h1>Wordplay emails</h1>
<p>Every message Wordplay sends, rendered from the same template the server
uses. Each is shown twice, because a mail client may impose either scheme.
Regenerate with <code>npm run emails</code>.</p>
${cards}
</body></html>`;
}

function sheetMarkdown(
    rendered: { kind: EmailKind; subject: string }[],
): string {
    const rows = rendered
        .map(
            ({ kind, subject }) =>
                `| \`${kind.id}\` | ${kind.what} | ${subject} | ${kind.trigger} | ${kind.to} | ${kind.localized ? 'yes' : 'no'} | ${kind.optional} |`,
        )
        .join('\n');
    return `# Emails

Every email Wordplay sends. Generated by \`npm run emails\` from
[functions/src/email/registry.ts](functions/src/email/registry.ts) — edit that
rather than this file. \`emailSheet.test.ts\` fails when the two drift.

All of it is sent from \`${Emails[0]?.from ?? ''}\`, replying to
\`${Emails[0]?.replyTo ?? ''}\`: a verified subdomain, so the reputation of
Wordplay's mail is independent of the Workspace mail sent from wordplay.dev.

Run \`npm run emails\` and open \`build/emails/index.html\` to see each one
rendered, in both light and dark.

| Email | What it is | Subject (English) | Sent when | To | Translated | Optional |
| --- | --- | --- | --- | --- | --- | --- |
${rows}
`;
}

export async function buildSheets(): Promise<{
    html: string;
    markdown: string;
}> {
    const rendered = [];
    for (const kind of Emails) {
        const { subject, html } = await renderSample(kind);
        rendered.push({ kind, subject, html });
    }
    return {
        html: await sheetHTML(rendered),
        // Through prettier, because `npm run format:check` covers the repo and
        // a generated file it would reformat drifts on every copy edit. The
        // same pass the font, logo and instrument generators end with.
        markdown: await format(sheetMarkdown(rendered), { parser: 'markdown' }),
    };
}

async function main() {
    const { html, markdown } = await buildSheets();
    mkdirSync(dirname(HtmlOut), { recursive: true });
    writeFileSync(HtmlOut, html);
    writeFileSync(MarkdownOut, markdown);
    console.log(`Wrote ${HtmlOut}`);
    console.log(`Wrote ${MarkdownOut}`);
}

// Only when run, so the sheet builder can be imported by its drift test.
if (
    process.argv[1] !== undefined &&
    import.meta.url.endsWith('contactSheet.ts')
)
    main().catch((error) => {
        console.error(error);
        process.exit(1);
    });
