export type Codepoint = {
    hex: number[];
    category: string;
    emoji: { group: string; subgroup: string } | undefined;
};

let codepoints: Codepoint[] | undefined = undefined;

export async function getCodepoints(): Promise<Codepoint[]> {
    if (codepoints !== undefined) return codepoints;

    // Generated by src/unicode/compress.ts. Run `npm run codes` to refresh.
    // Lines are: "<hex>;<category>" or
    // "<hex>;<category>;<emoji-group>;<emoji-subgroup>".
    const codesTxt: string = await fetch('/unicode/codes.txt').then((r) =>
        r.text(),
    );

    codepoints = [];
    for (const entry of codesTxt.split('\n')) {
        if (!entry) continue;
        const [code, category, group, subgroup] = entry.split(';');
        if (!code || !category) continue;
        codepoints.push({
            hex: code.split(' ').map((c) => parseInt(c, 16)),
            category,
            emoji:
                group && subgroup
                    ? {
                          group,
                          subgroup,
                      }
                    : undefined,
        });
    }

    // Sort by category, group, then subgroup, preserving file order within
    // each subgroup. Codepoints no longer carry names, so we drop the name-
    // based tiebreaker that used to keep results deterministic.
    codepoints.sort((a, b) => {
        if (a.category !== b.category)
            return a.category.localeCompare(b.category);
        if (a.emoji?.group !== b.emoji?.group)
            return (a.emoji?.group ?? '').localeCompare(b.emoji?.group ?? '');
        if (a.emoji?.subgroup !== b.emoji?.subgroup)
            return (a.emoji?.subgroup ?? '').localeCompare(
                b.emoji?.subgroup ?? '',
            );
        return 0;
    });

    return codepoints;
}

/** Format a codepoint sequence the same way codes.txt does so it matches the
 * keys in the per-locale {locale}-emojis.json files: each codepoint as upper-
 * case hex, zero-padded to a minimum of 4 digits, joined by spaces. */
export function codepointKey(hex: number[]): string {
    return hex
        .map((cp) => cp.toString(16).toUpperCase().padStart(4, '0'))
        .join(' ');
}

export async function getEmoji() {
    return (await getCodepoints()).filter((point) => point.emoji !== undefined);
}

/** Official Unicode categories: https://www.compart.com/en/unicode/category */
export const UnicodeCategories = [
    'Cc',
    'Cf',
    'Co',
    'Cs',
    'Ll',
    'Lm',
    'Lo',
    'Lt',
    'Lu',
    'Mc',
    'Me',
    'Mn',
    'Nd',
    'Nl',
    'No',
    'Pc',
    'Pd',
    'Pe',
    'Pf',
    'Pi',
    'Po',
    'Ps',
    'Sc',
    'Sk',
    'Sm',
    'So',
    'Zl',
    'Zp',
    'Zs',
];
