export type Codepoint = {
    hex: number[];
    name: string;
    category: string;
    emoji: { group: string; subgroup: string } | undefined;
};

let codepoints: Codepoint[] | undefined = undefined;

export async function getCodepoints(): Promise<Codepoint[]> {
    if (codepoints !== undefined) return codepoints;

    // Generated by unicode/compress.js. Run with Node >22.18 to update.
    const UnicodeDataTxt: string = await fetch('/unicode/codes.txt').then((r) =>
        r.text(),
    );

    codepoints = [];
    for (const entry of UnicodeDataTxt.split('\n')) {
        const [code, name, category, group, subgroup] = entry.split(';');
        codepoints.push({
            hex: code.split(' ').map((c) => parseInt(c, 16)),
            name: name.toLowerCase(),
            category,
            emoji:
                group && subgroup
                    ? {
                          group,
                          subgroup,
                      }
                    : undefined,
        });
    }

    // Sort by category, group, then subgroup, but preserve order otherwise.
    codepoints.sort((a, b) => {
        if (a.category !== b.category)
            return a.category.localeCompare(b.category);
        if (a.emoji?.group !== b.emoji?.group)
            return (a.emoji?.group ?? '').localeCompare(b.emoji?.group ?? '');
        if (a.emoji?.subgroup !== b.emoji?.subgroup)
            return (
                (a.emoji?.subgroup ?? '').localeCompare(
                    b.emoji?.subgroup ?? '',
                ) || a.name.localeCompare(b.name)
            );
        return 0;
    });

    return codepoints;
}

export async function getUnicodeNamed(name: string) {
    name = name.toLowerCase();
    return (await getCodepoints()).filter((point) => point.name.includes(name));
}

export async function getEmoji() {
    return (await getCodepoints()).filter((point) => point.emoji !== undefined);
}

/** Official Unicode categories: https://www.compart.com/en/unicode/category */
export const UnicodeCategories = [
    'Cc',
    'Cf',
    'Co',
    'Cs',
    'Ll',
    'Lm',
    'Lo',
    'Lt',
    'Lu',
    'Mc',
    'Me',
    'Mn',
    'Nd',
    'Nl',
    'No',
    'Pc',
    'Pd',
    'Pe',
    'Pf',
    'Pi',
    'Po',
    'Ps',
    'Sc',
    'Sk',
    'Sm',
    'So',
    'Zl',
    'Zp',
    'Zs',
];
