// Generated by unicode/compress.js. Run with Node.
import UnicodeDataTxt from './codes.txt?raw';
const codepoints = [];
for (const entry of UnicodeDataTxt.split('\n')) {
    const [code, name, category] = entry.split(';');
    codepoints.push({
        hex: parseInt(code, 16),
        name: name.toLowerCase(),
        category,
    });
}
export function getUnicodeNamed(name) {
    name = name.toLowerCase();
    return codepoints.filter((point) => point.name.includes(name));
}
//# sourceMappingURL=Unicode.js.map