/**
 * Emit a content hash for every locale asset the app fetches at runtime, so
 * `versioned()` can key a URL on what the file *says* rather than on which
 * build served it.
 *
 * The build version changes on every deploy, and only about a third of deploys
 * touch a locale — so keying on it made every other deploy re-download a
 * creator's whole locale (130-145KB brotli) to get back byte-identical text.
 * A content hash changes when, and only when, the content does.
 *
 * Runs after `npm run updates` and `npm run how` (both write assets counted
 * here) and before `vite build` (which bundles the module written here).
 */
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';

const StaticDirectory = 'static';
const LocalesDirectory = path.join(StaticDirectory, 'locales');
const OutputPath = path.join(
    'src',
    'db',
    'locales',
    'localeAssets.generated.ts',
);

/** Short enough to keep the table small, long enough that a collision across a
 *  few hundred files is not a thing that happens. */
function hash(contents: Buffer | string): string {
    return crypto
        .createHash('sha256')
        .update(contents)
        .digest('hex')
        .slice(0, 8);
}

/** Every `.json` under static/locales, at any depth, plus the changelog bundle
 *  the updates page fetches. Keyed by the URL path `versioned()` is handed, so
 *  the lookup needs no prefix surgery. */
function collectAssets(): Map<string, string> {
    const assets = new Map<string, string>();

    const walk = (directory: string): void => {
        for (const entry of fs.readdirSync(directory, {
            withFileTypes: true,
        })) {
            const full = path.join(directory, entry.name);
            // A locale's `sections/` are source, assembled into `<code>.json` at
            // build time. Nothing fetches them, and hashing them would double a
            // table that sits on every page's import graph.
            if (entry.isDirectory() && entry.name !== 'sections') walk(full);
            else if (entry.name.endsWith('.json')) {
                const url = `/${path.relative(StaticDirectory, full).split(path.sep).join('/')}`;
                assets.set(url, hash(fs.readFileSync(full)));
            }
        }
    };

    if (fs.existsSync(LocalesDirectory)) walk(LocalesDirectory);

    // Generated by `npm run updates`; absent on a tree that has not built yet,
    // in which case `versioned()` falls back and the page still works.
    const updates = path.join(StaticDirectory, 'updates.json');
    if (fs.existsSync(updates))
        assets.set('/updates.json', hash(fs.readFileSync(updates)));

    return assets;
}

function render(assets: Map<string, string>): string {
    const sorted = [...assets.entries()].sort(([a], [b]) =>
        a < b ? -1 : a > b ? 1 : 0,
    );
    const entries = sorted
        .map(([url, digest]) => `    '${url}': '${digest}',`)
        .join('\n');

    // Fallback for a path absent from the table. Derived from the table itself
    // so that adding a locale asset still busts the caches of anything the
    // generator could not see.
    const fallback = hash(
        sorted.map(([url, digest]) => `${url}:${digest}`).join('\n'),
    );

    return `/** Generated by \`npm run locale-assets\`. Do not edit.
 *
 * Content hash per locale asset, read by \`versioned()\`. This module holds only
 * data on purpose: \`versioned\` is reachable from \`UnknownName\` by way of
 * \`localeNameIndex\`, so a \`$app/environment\` import here would put a SvelteKit
 * virtual module on the basis graph and break \`npm run locales\` under tsx.
 */
export const LocaleAssetHashes: Record<string, string> = {
${entries}
};

/** Used when a path is not in the table above. */
export const LocaleAssetsVersion = '${fallback}';
`;
}

const assets = collectAssets();
const contents = render(assets);
const existing = fs.existsSync(OutputPath)
    ? fs.readFileSync(OutputPath, 'utf8')
    : undefined;

// Skip an unchanged write so a rebuild does not touch the file's mtime and
// retrigger every watcher downstream.
if (existing !== contents) {
    fs.mkdirSync(path.dirname(OutputPath), { recursive: true });
    fs.writeFileSync(OutputPath, contents);
}

console.log(`Hashed ${assets.size} locale assets into ${OutputPath}.`);
