import { HowToIDs, parseHowTo, type HowToBundleEntry } from '@concepts/HowTo';
import Log from '@util/verify-locales/Log';
import writeFormatted from '@util/verify-locales/writeFormatted';
import fs from 'fs';
import path from 'path';

/**
 * Generates a single `{locale}-how.json` bundle per locale from the authoring
 * `.txt` files in `static/locales/{locale}/how/`. The runtime loads this one file
 * instead of fetching each how-to individually (see LocalesDatabase.loadHowTos),
 * and consumes the precomputed concept/example index for guide deep linking.
 *
 * The `.txt` files remain the source of truth; this artifact is committed and
 * regenerated by the locale tooling.
 */

const howDir = (locale: string) =>
    path.join('static', 'locales', locale, 'how');

const bundlePath = (locale: string) =>
    path.join('static', 'locales', locale, `${locale}-how.json`);

/** Build (and write, if changed) the how-to bundle for a single locale. */
export async function buildHowToBundle(
    log: Log,
    locale: string,
): Promise<void> {
    const entries: HowToBundleEntry[] = [];

    for (const id of HowToIDs) {
        // Gallery how-tos are user-generated and not stored in /static.
        if (id === 'gallery-how-to') continue;

        // Use the locale's file, falling back to en-US so the bundle is complete.
        const localeFile = path.join(howDir(locale), `${id}.txt`);
        const fallbackFile = path.join(howDir('en-US'), `${id}.txt`);
        const file = fs.existsSync(localeFile)
            ? localeFile
            : fs.existsSync(fallbackFile)
              ? fallbackFile
              : undefined;
        if (file === undefined) continue;

        const text = fs.readFileSync(file, 'utf-8');
        const { how, body, error } = parseHowTo(id, text);
        if (how === null || body === null) {
            log.bad(2, `Invalid how-to '${id}' for ${locale}: ${error}`);
            continue;
        }

        entries.push({
            id: how.id,
            title: how.title,
            category: how.category,
            body,
            related: how.related,
        });
    }

    // Write only if changed (writeFormatted) so re-runs don't churn git.
    const wrote = await writeFormatted(
        bundlePath(locale),
        JSON.stringify(entries, null, 4),
    );
    if (wrote)
        log.good(2, `Wrote how-to bundle for ${locale} (${entries.length})`);
}

/** Build bundles for every locale directory. Used by the standalone `npm run how` script. */
export async function buildAllHowToBundles(log: Log): Promise<void> {
    const localeFolders = fs.readdirSync(path.join('static', 'locales'), {
        withFileTypes: true,
    });
    for (const folder of localeFolders) {
        if (folder.isDirectory()) await buildHowToBundle(log, folder.name);
    }
}

// Run directly (npm run how) — fail on invalid how-tos so a broken file breaks the build.
if (process.argv[1] && process.argv[1].endsWith('buildHowTos.ts')) {
    await buildAllHowToBundles(new Log(true));
}
