// Generate the "choose a language" invitation in every language, for the first-run
// language prompt (#1256).
//
// The prompt exists for people who can't read the interface they're looking at, so it
// has to greet them in their own language before they've chosen one — which means every
// locale's phrase has to be on screen at first paint, with no round-trip. Only en-US is
// bundled; the other locales' UI strings are ~550KB files fetched on demand, so reading
// them at runtime would mean thirty fetches to show thirty short phrases. Instead this
// lifts the one string out of each locale at build time, the way generateNameIndex lifts
// the name index.
//
// A locale whose `choose` is still unwritten is omitted rather than falling back to
// English: a rotating header that says "Choose a language" thirty times in a row would
// defeat the entire point of the feature.
//
// The phrases are text only, with no face alongside them. Carrying each locale's
// `ui.font.app` was the obvious idea, but the face registry has no face for Devanagari,
// Tamil, Telugu, Kannada, Gujarati, Bengali, Arabic, or Hebrew — those locales' UI
// already renders through OS fallback everywhere in the app, so the prompt is no
// different, and several locales' machine translations transliterated the face *name*
// ("Νότο Σανς"), which names nothing at all.
//
// The artifact is src/locale/choosePrompts.generated.ts, regenerated by
// `npm run locales-fix` and drift-checked by `npm run locales` and localeArtifactsSync.

import { toLocaleString } from '@locale/LocaleText';
import type LocaleText from '@locale/LocaleText';
import { withoutAnnotations } from '@locale/withoutAnnotations';
import type Log from '@util/verify-locales/Log';
import writeFormatted from '@util/verify-locales/writeFormatted';
import path from 'path';

/** Where the artifact is written, relative to the repo root. */
const PromptsFile = path.join('src', 'locale', 'choosePrompts.generated.ts');

/**
 * Build the table from every locale's text. Pure, so it can be tested on synthetic
 * locales. Locales with no written phrase are left out entirely — callers must treat a
 * missing entry as "this locale has nothing to say yet", not as an error.
 */
export function buildChoosePrompts(
    locales: LocaleText[],
): Record<string, string> {
    const prompts: Record<string, string> = {};
    // Sorted by code so the artifact is byte-stable across runs.
    for (const locale of [...locales].sort((a, b) =>
        toLocaleString(a).localeCompare(toLocaleString(b)),
    )) {
        const raw = locale.ui?.dialog?.locale?.choose;
        if (typeof raw !== 'string') continue;
        // An annotated string ($?/$!/$~) is untranslated, revised, or machine
        // translated. Only the first means "no phrase yet"; the other two are real
        // text, so strip the marker and keep them.
        if (raw.startsWith('$?')) continue;
        const phrase = withoutAnnotations(raw).trim();
        if (phrase.length === 0) continue;
        prompts[toLocaleString(locale)] = phrase;
    }
    return prompts;
}

/** Render the table as a TypeScript module, so it is bundled rather than fetched. */
function render(prompts: Record<string, string>): string {
    return [
        '// Generated by `npm run locales-fix` from each locale’s `ui.dialog.locale.choose`.',
        '// Do not edit: run `npm run locales-fix` instead. See generateChoosePrompts.ts.',
        '',
        '/** Locale code → that locale’s invitation to choose a language. */',
        'export const ChoosePrompts: Record<string, string> = ' +
            JSON.stringify(prompts, null, 4) +
            ';',
        '',
    ].join('\n');
}

/**
 * Write (or, with `write: false`, just check) the table. Returns whether the file on
 * disk differs from what this run would produce, so `npm run locales` can fail on drift.
 */
export default async function generateChoosePrompts(
    log: Log,
    locales: LocaleText[],
    write: boolean,
): Promise<boolean> {
    const prompts = buildChoosePrompts(locales);

    const changed = await writeFormatted(
        path.join(process.cwd(), PromptsFile),
        render(prompts),
        write,
        log,
    );

    if (changed && !write)
        log.bad(
            `${PromptsFile} is out of date with the locales. Run "npm run locales-fix" and commit it.`,
        );
    else
        log.good(
            `${changed ? 'Wrote' : 'No changes to'} ${PromptsFile} (${Object.keys(prompts).length} locales).`,
        );

    return changed;
}
