// Generate the word → locale index the languages dialog uses to answer "this project writes
// `Frase`, but which language calls something that?" without fetching every locale bundle.
//
// The words come from each locale's *basis*, built with itself as its own fallback (the same
// trick checkGlobalNames uses), so the index contains precisely the names that locale's
// definitions bind — not a guess scraped from JSON paths. Documentation is skipped: a name
// mentioned in a Spanish doc example is not a name Spanish binds, and suggesting a language
// on that basis would be wrong.
//
// Each locale's row holds only its *locale-specific* names: a name en-US binds at the same
// definition is dropped, because `Locales.getLocales()` appends the en-US fallback, so those
// names bind in every project whatever it declares and can never be the missing language.
// "At the same definition" is the load-bearing part — subtracting en-US's words wholesale
// would delete real answers, since a word can be an en-US input or member name and another
// locale's function name: `sin` is `Number.sine` in en-US and `List.sans` in es-MX, `y` is
// `Place.y` and `Boolean.and`, `combiner` is an input of `List.combine` and, in fr-FR, its
// name. Those references genuinely don't resolve until that locale is declared.
//
// The artifact is static/locales/names.json, regenerated by `npm run locales-fix` and
// drift-checked by `npm run locales`. It is advisory data — it drives suggestions, never
// analysis — so a stale copy costs a suggestion and nothing else.

import { Basis } from '@basis/Basis';
import concretize from '@locale/concretize';
import { toLocaleString } from '@locale/LocaleText';
import type LocaleText from '@locale/LocaleText';
import Locales from '@locale/Locales';
import type { LocaleNameIndex } from '@locale/localeNameIndex';
import Doc from '@nodes/Doc';
import Docs from '@nodes/Docs';
import Name from '@nodes/Name';
import Names from '@nodes/Names';
import type Node from '@nodes/Node';
import { KeywordIds } from '@parser/Keywords';
import type Log from '@util/verify-locales/Log';
import writeFormatted from '@util/verify-locales/writeFormatted';
import path from 'path';

/** Where the artifact is written, relative to the repo root. */
const IndexFile = path.join('static', 'locales', 'names.json');

/** One definition's names, keyed so the same definition can be found in another locale's
 *  basis. See {@link collectOwnedNames} for what the key is. */
type OwnedNames = Map<string, Set<string>>;

/**
 * Every name bound anywhere in `node`'s subtree, skipping documentation — docs contain
 * example code whose names say nothing about what this locale binds.
 */
function collectNames(node: Node, into: Set<string>) {
    if (node instanceof Docs || node instanceof Doc) return;
    if (node instanceof Name) {
        const name = node.getName();
        if (name !== undefined && name.length > 0) into.add(name);
        return;
    }
    for (const child of node.getChildren()) collectNames(child, into);
}

/**
 * The same names, but grouped by the definition that binds them, so two locales' names can
 * be compared definition by definition rather than as flat word bags.
 *
 * The key is the definition's position — which root, and how many `Names` nodes precede it
 * in that root — which identifies the same definition in every locale because the basis is
 * built by the same code from the same structure, with only the strings differing.
 */
function collectOwnedNames(
    node: Node,
    rootIndex: number,
    counter: { next: number },
    into: OwnedNames,
) {
    if (node instanceof Docs || node instanceof Doc) return;
    if (node instanceof Names) {
        const words = new Set<string>();
        for (const name of node.names) {
            const text = name.getName();
            if (text !== undefined && text.length > 0) words.add(text);
        }
        into.set(`${rootIndex}/${counter.next++}`, words);
        return;
    }
    for (const child of node.getChildren())
        collectOwnedNames(child, rootIndex, counter, into);
}

/** The names one locale's basis binds — flat and grouped by definition — and its keyword words. */
export function getLocaleWords(locale: LocaleText): {
    names: Set<string>;
    owned: OwnedNames;
    keywords: Set<string>;
} {
    // Its own fallback, so we capture the names this locale declares rather than en-US
    // fill-ins leaking in through the default fallback.
    const basis = new Basis(new Locales(concretize, [locale], locale));

    const names = new Set<string>();
    for (const root of basis.getRoots()) collectNames(root.root, names);

    // Keyed only from roots whose order is locale-independent. `getRoots()` also holds
    // `getAllFunctionDefinitions()`, and `functionsByType` is keyed by *localized* names, so
    // both its order and its length differ per locale — positions there would pair the wrong
    // definitions. Those functions live inside their type's structure anyway.
    const owned: OwnedNames = new Map();
    [...basis.shares.all, ...basis.getAllStructureDefinitions()].forEach(
        (definition, index) =>
            collectOwnedNames(definition, index, { next: 0 }, owned),
    );

    const keywords = new Set<string>();
    for (const id of KeywordIds) {
        const raw = locale.keyword[id];
        if (typeof raw !== 'string') continue;
        // Strip the write-status annotation the locale files carry ($?/$!/$~).
        const word = raw.replace(/^\$[~?!]/, '').trim();
        if (word.length > 0) keywords.add(word);
    }

    return { names, owned, keywords };
}

/**
 * Build the index from every locale's text. Pure, so it can be tested on synthetic locales;
 * `log` only reports locales left unstripped. Throws if en-US isn't among them, rather than
 * quietly emitting an unstripped artifact that would then fail the drift check forever.
 */
export function buildNameIndex(
    locales: LocaleText[],
    log?: Log,
): LocaleNameIndex {
    // Sorted by code and by word so the artifact is byte-stable across runs.
    const sorted = [...locales].sort((a, b) =>
        toLocaleString(a).localeCompare(toLocaleString(b)),
    );
    const words = new Map(
        sorted.map((locale) => [
            toLocaleString(locale),
            getLocaleWords(locale),
        ]),
    );

    // By code, not by identity with the imported DefaultLocale, so synthetic locales work.
    const english = words.get('en-US');
    if (english === undefined)
        throw new Error(
            "Can't build the language name index without en-US: every other locale's names are defined relative to it.",
        );

    const names: Record<string, string> = {};
    const keywords: Record<string, string> = {};
    for (const [code, locale] of words) {
        names[code] = join(
            code === 'en-US'
                ? locale.names
                : localeSpecific(code, locale, english, log),
        );
        keywords[code] = join(locale.keywords);
    }

    return { names, keywords };
}

/**
 * A locale's names minus the ones en-US binds at the same definition. A word bound at a
 * definition en-US spells differently stays: that's the case where declaring this locale is
 * what makes the reference resolve.
 */
function localeSpecific(
    code: string,
    locale: { names: Set<string>; owned: OwnedNames },
    english: { owned: OwnedNames },
    log?: Log,
): Set<string> {
    // If the two bases didn't line up, the keys don't identify the same definitions and the
    // subtraction would be guesswork. Keep everything: a bigger artifact is a far cheaper
    // failure than a name silently dropped from the one table that can suggest it.
    if (locale.owned.size !== english.owned.size) {
        log?.warning(
            `${code}'s definitions didn't line up with en-US's (${locale.owned.size} vs ${english.owned.size}), so its names weren't reduced.`,
        );
        return locale.names;
    }

    // A word is redundant only if *every* definition binding it here also binds it in en-US.
    // One definition where they differ is enough to keep it: that's the reference that
    // wouldn't resolve without this locale.
    const redundant = new Map<string, boolean>();
    for (const [key, words] of locale.owned) {
        const englishWords = english.owned.get(key);
        for (const word of words)
            redundant.set(
                word,
                (redundant.get(word) ?? true) &&
                    englishWords?.has(word) === true,
            );
    }

    return new Set(
        [...locale.names].filter((word) => redundant.get(word) !== true),
    );
}

/** Space-join words for the compact artifact, dropping any that contain whitespace or still
 *  carry a write-status annotation. Names and keyword words are single tokens (checkNames and
 *  the keyword check enforce it), but `getInputLocales` builds input names without stripping
 *  annotations, so an unwritten one can reach here as a literal `$?word`. */
function join(words: Set<string>): string {
    return Array.from(words)
        .filter((word) => !/\s/.test(word) && !word.startsWith('$'))
        .sort()
        .join(' ');
}

/**
 * Write (or, with `write: false`, just check) the index. Returns whether the file on disk
 * differs from what this run would produce, so `npm run locales` can fail on drift.
 */
export default async function generateNameIndex(
    log: Log,
    locales: LocaleText[],
    write: boolean,
): Promise<boolean> {
    let index: LocaleNameIndex;
    try {
        index = buildNameIndex(locales, log);
    } catch (error) {
        // Either a locale has a name that isn't a valid identifier — a machine translation can
        // produce one, and building that locale's definitions then throws — or en-US is missing.
        // Either way the artifact can't be built, so report it and leave the committed one
        // alone rather than writing something wrong. `fix` doesn't fail on errors, so it still
        // completes and repairs the names; `verify` fails, which is what a locale that can't
        // build its own basis deserves.
        log.bad(
            `Couldn't build the language name index. Run "npm run locales-fix". (${error instanceof Error ? error.message : String(error)})`,
        );
        return false;
    }

    const changed = await writeFormatted(
        path.join(process.cwd(), IndexFile),
        JSON.stringify(index),
        write,
        log,
    );

    if (changed && !write)
        log.bad(
            `${IndexFile} is out of date with the locales. Run "npm run locales-fix" and commit it.`,
        );
    else
        log.good(
            `${changed ? 'Wrote' : 'No changes to'} ${IndexFile} (${Object.keys(index.names).length} locales).`,
        );

    return changed;
}
