/**
 * Reads the generated `static/schemas/LocaleText.json` and emits
 * `src/locale/templateInputs.generated.ts`: a small TypeScript module with
 * just the per-field declared input names and the terminology key list.
 *
 * Why a codegen step instead of importing the JSON schema directly?
 * - `static/` is Vite's public directory. Importing from it in browser code
 *   triggers a Vite warning ("Assets in public directory cannot be imported
 *   from JavaScript") and bundles a ~330 KB JSON blob for ~3 KB of data.
 * - The schema is the right source of truth, but the *bundled* artifact is
 *   the codegen output below — tiny, type-checked, no runtime parsing.
 *
 * Run by `npm run locale-schema` (chained after the schema regen so it
 * always sees the latest types).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/** Minimal shape of the JSON Schema fragments we walk. We treat the schema
 *  as untyped JSON elsewhere; this narrow type is enough for the recursion. */
type SchemaNode = {
    $ref?: string;
    properties?: Record<string, SchemaNode>;
    items?: SchemaNode | SchemaNode[];
};

type Schema = {
    definitions?: Record<string, SchemaNode>;
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// scripts and modules in src/util/verify-locales/ live four levels deep.
const ROOT = path.resolve(__dirname, '../../..');
const SCHEMA_PATH = path.join(ROOT, 'static/schemas/LocaleText.json');
const OUT_PATH = path.join(ROOT, 'src/locale/templateInputs.generated.ts');

const schema: Schema = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf8'));

function parseTemplateRef(ref: string): string[] | undefined {
    const match = ref.match(/^Template<\[(.*)\]>$/);
    if (!match) return undefined;
    const body = match[1].trim();
    if (body === '') return [];
    const names: string[] = [];
    for (const part of body.split(',')) {
        const m = part.trim().match(/^"(.*)"$/);
        if (!m) return undefined;
        names.push(m[1]);
    }
    return names;
}

const inputsByField = new Map<string, string[]>();

function visit(
    node: SchemaNode | undefined,
    localePath: string[],
    refStack: string[],
): void {
    if (!node || typeof node !== 'object') return;
    if (typeof node.$ref === 'string') {
        const refName = decodeURIComponent(
            node.$ref.replace('#/definitions/', ''),
        );
        const names = parseTemplateRef(refName);
        if (names !== undefined) {
            inputsByField.set(localePath.join('.'), names);
            return;
        }
        if (refStack.includes(refName)) return;
        const def = schema.definitions?.[refName];
        if (def) visit(def, localePath, [...refStack, refName]);
        return;
    }
    if (node.properties) {
        for (const [k, v] of Object.entries(node.properties))
            visit(v, [...localePath, k], refStack);
    }
    if (node.items) {
        if (Array.isArray(node.items))
            for (const it of node.items) visit(it, localePath, refStack);
        else visit(node.items, localePath, refStack);
    }
}

visit(schema.definitions?.LocaleText, [], []);

const termRoot = schema.definitions?.LocaleText?.properties?.term?.properties;
const terminologyNames: string[] = Object.keys(termRoot ?? {}).sort();

const entries: [string, string[]][] = [...inputsByField.entries()].sort(
    (a, b) => a[0].localeCompare(b[0]),
);

const body =
    `// AUTO-GENERATED by src/util/verify-locales/generate-template-inputs.ts.
// Do not edit by hand — re-run \`npm run locale-schema\` to refresh.
//
// Source of truth: the \`Template<['a','b']>\` annotations in src/locale/*.ts,
// which round-trip through ts-json-schema-generator into static/schemas/
// LocaleText.json. This module flattens that JSON down to the two pieces of
// data the runtime and editor actually need: declared inputs per field, and
// the set of valid terminology keys.

/** Field path -> ordered list of declared input names. */
export const DECLARED_INPUTS: Readonly<Record<string, readonly string[]>> = {
` +
    entries
        .map(
            ([k, v]) =>
                `    '${k}': [${v.map((n) => `'${n}'`).join(', ')}],`,
        )
        .join('\n') +
    `
};

/** Names valid in \`$name\` mentions as terminology references. */
export const TERMINOLOGY_NAMES: readonly string[] = [
` +
    terminologyNames.map((n) => `    '${n}',`).join('\n') +
    `
];
`;

// Skip the write when the on-disk content already matches. Always-writing
// touches mtime and can prime feedback loops with file watchers (e.g. a
// stray nodemon on src/locale that doesn't ignore this generated file would
// re-trigger create-schemas → write → re-trigger → ... forever, which then
// floods Vite HMR).
const existing = fs.existsSync(OUT_PATH)
    ? fs.readFileSync(OUT_PATH, 'utf8')
    : undefined;
if (existing === body) {
    console.log(
        `${OUT_PATH} unchanged (${entries.length} fields, ${terminologyNames.length} terms)`,
    );
} else {
    fs.writeFileSync(OUT_PATH, body);
    console.log(
        `Wrote ${OUT_PATH} (${entries.length} fields, ${terminologyNames.length} terms)`,
    );
}
