// Generate one web app manifest per locale, so an installed Wordplay is named and
// described in the language its creator chose (#564).
//
// A manifest can't carry more than one language — there's no media-query or
// content-negotiation equivalent for it — so localizing means emitting a file per
// locale and pointing each page at its own. That's cheap here because every
// locale-prefixed page is already prerendered (see the `entries` export in
// src/routes/[[locale]]/+page.ts) and hooks.server.ts already substitutes that
// locale's strings into app.html; the manifest href is one more substitution.
//
// `id` is deliberately the same in every file. It's what a browser uses to decide
// whether an install is the same app as one already installed, so sharing it means
// the thirty locales are one Wordplay whose name follows the locale it was installed
// from, rather than thirty separate apps competing for the same home screen.
//
// The artifacts are static/manifests/<code>.webmanifest, regenerated by
// `npm run locales-fix` and drift-checked by `npm run locales` and localeArtifactsSync.

import { getLanguageDirection } from '@locale/LanguageCode';
import type LocaleText from '@locale/LocaleText';
import { toLocaleString } from '@locale/LocaleText';
import { withoutAnnotations } from '@locale/withoutAnnotations';
import { getManifestPath } from '@locale/SupportedLocales';
import type Log from '@util/verify-locales/Log';

import writeFormatted from '@util/verify-locales/writeFormatted';
import fs from 'fs';
import path from 'path';

/** Where the artifacts are written, relative to the repo root. Everything in
 *  `static/` is served from the root, so this folder is exactly the URL path
 *  {@link getManifestPath} produces. */
export const ManifestsFolder = path.join('static', 'manifests');

/** The file a locale's manifest is written to, derived from the URL the pages
 *  link to so the two can't drift apart. */
function getManifestFile(code: string): string {
    return path.basename(getManifestPath(code));
}

/** The install icons, shared by every locale: the mark carries no text. */
const Icons = [
    {
        src: '/icons/android-chrome-192x192.png',
        sizes: '192x192',
        type: 'image/png',
    },
    {
        src: '/icons/android-chrome-512x512.png',
        sizes: '512x512',
        type: 'image/png',
    },
    {
        src: '/icons/maskable-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
    },
];

/** Just the fields a manifest is built from. Structural rather than the whole
 *  `LocaleText`, so tests can state a case in four lines instead of building a
 *  complete locale — the same shape hooks.server.ts gives its parsed JSON. */
export type ManifestSource = Pick<LocaleText, 'language' | 'regions'> & {
    glossary?: { wordplay?: { word?: string | undefined } };
    system?: { appDescription?: string | undefined };
};

/** A string with its annotations stripped, or undefined if nothing is left —
 *  an unwritten string is a bare `$?`, which strips to nothing at all. */
function written(text: string | undefined): string | undefined {
    const stripped = withoutAnnotations(text ?? '').trim();
    return stripped.length === 0 ? undefined : stripped;
}

/**
 * Build one locale's manifest. Pure, so it can be tested on synthetic locales.
 *
 * Falls back to en-US string by string, the same way hooks.server.ts does for
 * the rest of app.html: a locale that hasn't been translated yet should install
 * as an English Wordplay rather than as a nameless one.
 */
export function buildManifest(
    locale: ManifestSource,
    fallback: ManifestSource,
): Record<string, unknown> {
    const code = toLocaleString(locale);
    const name =
        written(locale.glossary?.wordplay?.word) ??
        written(fallback.glossary?.wordplay?.word) ??
        '';
    const description =
        written(locale.system?.appDescription) ??
        written(fallback.system?.appDescription) ??
        '';
    return {
        // Same in every locale: one installed app, not thirty.
        id: '/',
        name,
        short_name: name,
        description,
        // The language alone, not the full locale code: several locales name more
        // than one region (`ta-IN-LK-SG`), which is not a valid BCP 47 tag. This
        // matches the `lang` the layout sets on the document.
        lang: locale.language,
        dir: getLanguageDirection(locale.language),
        // Launch into this locale explicitly, so the installed app opens in the
        // language it was installed from regardless of stored settings.
        start_url: `/${code}`,
        // The whole app, so following a link to another locale or an unprefixed
        // route stays inside the installed window instead of opening a browser.
        scope: '/',
        display: 'standalone',
        // A manifest takes one color; app.html declares the light/dark pair as
        // `theme-color` metas, which browsers prefer for the window itself. This
        // is the light value, matching --white-light.
        theme_color: '#ffffff',
        background_color: '#ffffff',
        icons: Icons,
    };
}

/**
 * Write (or, with `write: false`, just check) every locale's manifest. Returns
 * whether anything on disk differs from what this run would produce, so
 * `npm run locales` can fail on drift.
 */
export default async function generateManifests(
    log: Log,
    locales: LocaleText[],
    write: boolean,
): Promise<boolean> {
    // Every locale falls back to en-US for anything it hasn't written yet.
    const fallback = locales.find((l) => toLocaleString(l) === 'en-US');
    if (fallback === undefined) {
        log.bad('No en-US locale to fall back to; skipping app manifests.');
        return false;
    }

    const folder = path.join(process.cwd(), ManifestsFolder);
    if (write && !fs.existsSync(folder))
        fs.mkdirSync(folder, { recursive: true });

    let changed = false;
    const expected = new Set<string>();

    // Sorted by code so a run's log and any failure read in a stable order.
    for (const locale of [...locales].sort((a, b) =>
        toLocaleString(a).localeCompare(toLocaleString(b)),
    )) {
        const code = toLocaleString(locale);
        const file = getManifestFile(code);
        expected.add(file);
        const wrote = await writeFormatted(
            path.join(folder, file),
            JSON.stringify(buildManifest(locale, fallback), null, 4),
            write,
            log,
        );
        if (wrote) changed = true;
    }

    // A locale that's been renamed or removed leaves a manifest behind that no
    // page links to; drop it rather than shipping a file nothing can reach.
    const stale = fs.existsSync(folder)
        ? fs.readdirSync(folder).filter((file) => !expected.has(file))
        : [];
    for (const file of stale) {
        changed = true;
        if (write) fs.unlinkSync(path.join(folder, file));
        else
            log.bad(
                `${path.join(ManifestsFolder, file)} is for a locale that no longer exists.`,
            );
    }

    if (changed && !write)
        log.bad(
            `${ManifestsFolder} is out of date with the locales. Run "npm run locales-fix" and commit it.`,
        );
    else
        log.good(
            `${changed ? 'Wrote' : 'No changes to'} ${ManifestsFolder} (${expected.size} locales).`,
        );

    return changed;
}
