import dotenv from 'dotenv';

/**
 * Load environment for the locales CLI, as a side-effect import placed first in
 * `start.ts` so it runs before anything reads `process.env` (e.g.
 * `ANTHROPIC_API_KEY` for the Claude backend).
 *
 * Two files, earlier wins, neither overrides variables already set in the shell
 * or CI:
 *  - `.env.local` — gitignored developer secrets. NOT regenerated by
 *    `npm run env` (which only rewrites `.env` from `.env.<project>`), so keys
 *    placed here survive env switches and deploys. Put ANTHROPIC_API_KEY here.
 *  - `.env` — project config, regenerated per Firebase project.
 *
 * A missing file is ignored.
 */
dotenv.config({ path: ['.env.local', '.env'] });
