// Generated by `npm run instruments-build` from scripts/instruments/manifest.ts.
// Do not edit: run the command instead. Committed because the runtime imports
// it and because it is the record of which zones the shipped mp3s cover.

/** One recording, and the note it was played at. */
export type Zone = {
    /** Path under `static/instruments`. */
    file: string;
    /** MIDI note of the recording. */
    root: number;
    /** Tuning correction in cents, to bring the recording to A440. */
    detune: number;
    /** Seconds of audio. */
    duration: number;
};

/** Zones per instrument id, ascending by root. Instruments absent here play
 * their synthesized recipe: see `SynthesisOnly` in the manifest for why. */
export const Zones: Record<string, Zone[]> = {
    piano: [
        { file: 'piano/36.mp3', root: 36, detune: 6, duration: 3.5 },
        { file: 'piano/42.mp3', root: 42, detune: 3, duration: 3.5 },
        { file: 'piano/48.mp3', root: 48, detune: 1, duration: 3.5 },
        { file: 'piano/54.mp3', root: 54, detune: 1, duration: 3.5 },
        { file: 'piano/60.mp3', root: 60, detune: -1, duration: 3.5 },
        { file: 'piano/66.mp3', root: 66, detune: 0, duration: 3.5 },
        { file: 'piano/72.mp3', root: 72, detune: 2, duration: 3.5 },
        { file: 'piano/78.mp3', root: 78, detune: -1, duration: 3.5 },
        { file: 'piano/84.mp3', root: 84, detune: 3, duration: 3.5 },
    ],
    saxophone: [
        { file: 'saxophone/36.mp3', root: 36, detune: 0, duration: 2.5 },
        { file: 'saxophone/42.mp3', root: 42, detune: 0, duration: 2.5 },
        { file: 'saxophone/48.mp3', root: 48, detune: 0, duration: 2.5 },
        { file: 'saxophone/54.mp3', root: 54, detune: 0, duration: 2.5 },
        { file: 'saxophone/60.mp3', root: 60, detune: 0, duration: 2.5 },
        { file: 'saxophone/66.mp3', root: 66, detune: 0, duration: 2.5 },
        { file: 'saxophone/72.mp3', root: 72, detune: 0, duration: 2.5 },
    ],
    bell: [
        { file: 'bell/48.mp3', root: 48, detune: 0, duration: 3.5 },
        { file: 'bell/54.mp3', root: 54, detune: 0, duration: 3.5 },
        { file: 'bell/60.mp3', root: 60, detune: 0, duration: 3.5 },
        { file: 'bell/64.mp3', root: 64, detune: 0, duration: 3.5 },
    ],
    didgeridoo: [
        { file: 'didgeridoo/37.mp3', root: 37, detune: -6, duration: 3.0 },
    ],
    violin: [
        { file: 'violin/55.mp3', root: 55, detune: 3, duration: 2.5 },
        { file: 'violin/64.mp3', root: 64, detune: -4, duration: 2.5 },
        { file: 'violin/72.mp3', root: 72, detune: 3, duration: 2.5 },
        { file: 'violin/79.mp3', root: 79, detune: -1, duration: 2.5 },
        { file: 'violin/88.mp3', root: 88, detune: -16, duration: 2.5 },
        { file: 'violin/96.mp3', root: 96, detune: 1, duration: 2.5 },
    ],
    flute: [
        { file: 'flute/60.mp3', root: 60, detune: 2, duration: 2.5 },
        { file: 'flute/69.mp3', root: 69, detune: 0, duration: 2.5 },
        { file: 'flute/76.mp3', root: 76, detune: 3, duration: 2.5 },
        { file: 'flute/84.mp3', root: 84, detune: -2, duration: 2.5 },
        { file: 'flute/93.mp3', root: 93, detune: -6, duration: 2.5 },
    ],
    trumpet: [
        { file: 'trumpet/53.mp3', root: 53, detune: 2, duration: 2.5 },
        { file: 'trumpet/60.mp3', root: 60, detune: -2, duration: 2.5 },
        { file: 'trumpet/67.mp3', root: 67, detune: -1, duration: 2.5 },
        { file: 'trumpet/74.mp3', root: 74, detune: -2, duration: 2.5 },
        { file: 'trumpet/81.mp3', root: 81, detune: 0, duration: 2.5 },
    ],
    drums: [
        { file: 'drums/36.mp3', root: 36, detune: 0, duration: 2.0 },
        { file: 'drums/38.mp3', root: 38, detune: 0, duration: 1.359 },
        { file: 'drums/42.mp3', root: 42, detune: 0, duration: 1.237 },
        { file: 'drums/49.mp3', root: 49, detune: 0, duration: 2.0 },
        { file: 'drums/50.mp3', root: 50, detune: 0, duration: 2.0 },
        { file: 'drums/56.mp3', root: 56, detune: 0, duration: 1.154 },
    ],
};

/** The instruments that ship recordings. */
export const SampledInstruments = Object.keys(Zones);
