name: Deploy Firebase hosting to production
on:
    push:
        branches:
            - main
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm ci
            - run: echo "${{ secrets.ENV_PROD }}" > .env.wordplay-prod
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WORDPLAY_PROD }}
                  channelId: live
                  projectId: wordplay-prod
                  firebaseToolsVersion: 13.35.1
