name: Deploy Firebase hosting to staging
on: pull_request
permissions:
    checks: write
    contents: read
    pull-requests: write
jobs:
    build_and_preview:
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm ci
            - run: echo "${{ secrets.ENV_DEV }}" > .env.wordplay-dev
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WORDPLAY_DEV }}
                  projectId: wordplay-dev
