name: Verify PR - check types, accessibility, syntax, semantics, and locales
on:
    pull_request:
        branches: ['main']
jobs:
    unit:
        uses: ./.github/workflows/unit.yml

    playwright:
        uses: ./.github/workflows/playwright.yml
        secrets: inherit
